INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Explosion and rupture of pressurized-gas tank, init encntr',NULL),
	 ('Beauty','Passenger of snowmobile injured in traffic accident',NULL),
	 ('Toys','Contusion of unsp index finger w/o damage to nail, subs',NULL),
	 ('Beauty','Chronic osteomyelitis with draining sinus, shoulder',NULL),
	 ('Grocery','Polyosteoarthritis',NULL),
	 ('Tools','Unsp fx shaft of r tibia, 7thM',NULL),
	 ('Electronics','Lacerat flexor musc/fasc/tend l idx fngr at forarm lv, subs',NULL),
	 ('Movies','Oth comp of fb acc left in body following remov cath/pack',NULL),
	 ('Movies','Cicatricial ectropion of unspecified eye, unspecified eyelid',NULL),
	 ('Automotive','Injury of unsp nerve at ankle and foot level, left leg, init',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Games','Poisoning by other psychostimulants, assault, init encntr',NULL),
	 ('Tools','Milt op w acc deton onboard marine weapons, civilian, init',NULL),
	 ('Toys','Toxic effect of ingested berries, self-harm, init',NULL),
	 ('Books','Displacement of artificial heart',NULL),
	 ('Automotive','Other specified malignant neoplasm of skin of breast',NULL),
	 ('Garden','Diseases of the resp sys comp pregnancy, first trimester',NULL),
	 ('Games','Displaced fracture of anterior process of left calcaneus',NULL),
	 ('Toys','Encounter for adoption services',NULL),
	 ('Grocery','Dislocation of unsp internal joint prosthesis, subs encntr',NULL),
	 ('Electronics','Abrasion of unspecified back wall of thorax, subs encntr',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Beauty','Ulcer of penis',NULL),
	 ('Kids','Spotted fever, unspecified',NULL),
	 ('Grocery','Corns and callosities',NULL),
	 ('Health','Nondisp spiral fx shaft of rad, unsp arm, 7thQ',NULL),
	 ('Electronics','Accidental discharge of hunting rifle',NULL),
	 ('Toys','Rheu arthritis of left hip w involv of organs and systems',NULL),
	 ('Sports','Drug/chem diabetes w diabetic neuropathic arthropathy',NULL),
	 ('Outdoors','Carbuncle, unspecified',NULL),
	 ('Beauty','Nondisp fx of navicular of r foot, subs for fx w nonunion',NULL),
	 ('Health','Burn of third degree of other site of trunk',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Computers','Sleep apnea',NULL),
	 ('Shoes','Oral mucositis (ulcerative), unspecified',NULL),
	 ('Music','Accidental malfunction of hunting rifle',NULL),
	 ('Baby','Nondisp fx of unsp tibial spin, 7thQ',NULL),
	 ('Electronics','Sunburn of third degree',NULL),
	 ('Baby','Laceration of superior mesenteric vein',NULL),
	 ('Games','Superficial foreign body, right ankle, sequela',NULL),
	 ('Automotive','Major laceration of left carotid artery, sequela',NULL),
	 ('Outdoors','Displaced fracture of acromial process, left shoulder',NULL),
	 ('Movies','Other fracture of lower end of left tibia',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Fracture of unsp part of left clavicle, init for clos fx',NULL),
	 ('Outdoors','Eosinophilia',NULL),
	 ('Kids','Car passenger injured in collision w van nontraf, subs',NULL),
	 ('Garden','Oth fx low end unsp femr, 7thR',NULL),
	 ('Games','Epidural hemorrhage w LOC >24 hr w ret consc lev, subs',NULL),
	 ('Health','Disp fx of lateral condyle of unsp femr, 7thP',NULL),
	 ('Jewelry','Terrorism involving suicide bomber, civilian injured, subs',NULL),
	 ('Games','Type 2 diabetes mellitus with diabetic nephropathy',NULL),
	 ('Sports','Dysphasia following unspecified cerebrovascular disease',NULL),
	 ('Sports','Gestational hypertension without significant proteinuria',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Games','Fx femur fol insrt ortho implnt/prosth/bone plt, right leg',NULL),
	 ('Books','Unsp traum nondisp spondylolysis of 7th cervcal vert, 7thG',NULL),
	 ('Books','Superficial frostbite of unspecified hand',NULL),
	 ('Toys','Unspecified superficial injury of other finger, subs encntr',NULL),
	 ('Baby','Car driver injured in collision w SUV nontraf, sequela',NULL),
	 ('Shoes','Corrosion of second degree back of unspecified hand',NULL),
	 ('Shoes','Disorders of esophagus in diseases classified elsewhere',NULL),
	 ('Movies','Oth fx upper end of unsp ulna, subs for clos fx w routn heal',NULL),
	 ('Shoes','Nondisplaced fracture of base of other metacarpal bone',NULL),
	 ('Computers','War operations involving oth dest arcrft, military personnel',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Baby','Open bite of eyelid and periocular area',NULL),
	 ('Shoes','Fall from oth rolling-type pedestrian conveyance, subs',NULL),
	 ('Industrial','Strain of musc/tend at lower leg level, unsp leg',NULL),
	 ('Grocery','Oclr lac w/o prolaps/loss of intraoc tissue, unsp eye, subs',NULL),
	 ('Grocery','Exposure to bed fire due to oth burning material, subs',NULL),
	 ('Beauty','Underfeeding of newborn',NULL),
	 ('Toys','Unspecified Eustachian tube disorder, bilateral',NULL),
	 ('Tools','Person outside pk-up/van inj in nonclsn trnsp acc nontraf',NULL),
	 ('Health','Nondisp fx of med malleolus of unsp tibia, 7thR',NULL),
	 ('Computers','Drowning and submersion due to canoe or kayak overturning',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Outdoors','Poisoning by MAO inhib antidepressants, undetermined, subs',NULL),
	 ('Computers','Contusion of unspecified part of small intestine',NULL),
	 ('Toys','Vis def/sptl nglct following ntrm subarachnoid hemorrhage',NULL),
	 ('Outdoors','Open bite of right ring finger w damage to nail, init encntr',NULL),
	 ('Automotive','Unsp pedl cyclst inj pk-up truck, pk-up/van in traf, sequela',NULL),
	 ('Outdoors','Adverse effect of other psychotropic drugs',NULL),
	 ('Home','External constriction of right back wall of thorax, init',NULL),
	 ('Games','Toxic effect of ethanol, intentional self-harm',NULL),
	 ('Books','Unspecified physeal fracture of phalanx of left toe, 7thK',NULL),
	 ('Baby','Strain of left Achilles tendon',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Beauty','Inj lesser saphenous vein at lower leg level, unsp leg, subs',NULL),
	 ('Movies','Displacement of prosth dev/implnt/grft of genital tract',NULL),
	 ('Grocery','Path fracture, left finger(s), subs for fx w routn heal',NULL),
	 ('Computers','Presence of other specified functional implants',NULL),
	 ('Tools','Blindness, one eye, low vision other eye, unspecified eyes',NULL),
	 ('Outdoors','Nondisp commnt fx shaft of unsp fibula, 7thJ',NULL),
	 ('Books','Other bursal cyst, unspecified site',NULL),
	 ('Kids','Oth injury to person on ground due to air trnsp acc, subs',NULL),
	 ('Books','Activity, wrestling',NULL),
	 ('Home','Other mechanical complication of unspecified vascular grafts',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Health','Fracture of malar, maxillary and zygoma bones, unspecified',NULL),
	 ('Movies','Civilian aircraft in air trnsp accident w military aircraft',NULL),
	 ('Clothing','Complication of inhalation therapy, subsequent encounter',NULL),
	 ('Tools','Strain of adductor muscle, fascia and tendon of right thigh',NULL),
	 ('Books','Oth fx of low end unsp rad, 7thJ',NULL),
	 ('Baby','Displacement of cardiac electrode, initial encounter',NULL),
	 ('Clothing','Unspecified injury of radial artery at forearm level',NULL),
	 ('Computers','Other contact with alligator, subsequent encounter',NULL),
	 ('Music','Hallucinogen dependence w unsp hallucinogen-induced disorder',NULL),
	 ('Games','Unspecified juvenile rheumatoid arthritis, left elbow',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Games','Poisn by centr-acting/adren-neurn-block agnt, slf-hrm, sqla',NULL),
	 ('Movies','Stress fracture, other site, sequela',NULL),
	 ('Jewelry','Intermittent exophthalmos, bilateral',NULL),
	 ('Baby','Melanoma in situ of anal skin',NULL),
	 ('Health','Inj muscle, fascia and tendon of unsp hip, subs encntr',NULL),
	 ('Outdoors','Displaced fracture of medial condyle of unspecified femur',NULL),
	 ('Industrial','Displaced midcervical fx l femur, init for opn fx type I/2',NULL),
	 ('Jewelry','Disp fx of medial phalanx of left ring finger, init',NULL),
	 ('Automotive','Recurrent dislocation of patella, left knee',NULL),
	 ('Toys','Milt op involving fragments from weapons, military personnel',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Clothing','Inj oth blood vessels at shldr/up arm, unsp arm',NULL),
	 ('Health','Cortical age-related cataract, unspecified eye',NULL),
	 ('Beauty','History of uterine scar from previous surgery',NULL),
	 ('Automotive','Oth comp specific to multiple gest, first trimester, fetus 2',NULL),
	 ('Toys','Unspecified sprain of left great toe, subsequent encounter',NULL),
	 ('Movies','Nondisp fx of med malleolus of unsp tibia, 7thB',NULL),
	 ('Kids','Other nondisp fx of lower end of right humerus, sequela',NULL),
	 ('Grocery','Unsp superficial injury of unspecified great toe, sequela',NULL),
	 ('Health','Person outside bus inj in clsn w rail trn/veh nontraf, init',NULL),
	 ('Clothing','Toxic effect of venom of scorpion, self-harm, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Radicular cyst',NULL),
	 ('Music','Intentional collision of motor vehicle w train, init encntr',NULL),
	 ('Automotive','Open wound of other specified parts of neck',NULL),
	 ('Music','Nondisp transverse fracture of shaft of unsp femur, init',NULL),
	 ('Automotive','Laceration w/o foreign body of oth part of neck, subs encntr',NULL),
	 ('Health','Small kidney of unknown cause',NULL),
	 ('Home','Nondisp fx of neck of fourth MC bone, left hand, sequela',NULL),
	 ('Industrial','Other specified acquired deformities of left forearm',NULL),
	 ('Jewelry','Unsp ultralt/microlt/pwr-glider acc injuring occupant, init',NULL),
	 ('Jewelry','Nondisp oblique fx shaft of l rad, init for opn fx type I/2',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Outdoors','Toxic effect of halogenated insecticides',NULL),
	 ('Grocery','Unspecified degenerative disorder of globe',NULL),
	 ('Garden','Maternal care for oth rhesus isoimmun, unsp tri, fetus 5',NULL),
	 ('Industrial','Traumatic amputation of ankle and foot',NULL),
	 ('Games','External constriction of right elbow',NULL),
	 ('Tools','Obstructed labor due to oth malpos and malpresent, fetus 5',NULL),
	 ('Games','Military operations involving biological weapons, civilian',NULL),
	 ('Movies','Sympathetic uveitis, unspecified eye',NULL),
	 ('Shoes','Periumbilical pain',NULL),
	 ('Games','Disp fx of lateral condyle of l tibia, 7thQ',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Garden','Disp fx of shaft of unsp MC bone, subs for fx w delay heal',NULL),
	 ('Books','Pathological fracture, unspecified ulna and radius',NULL),
	 ('Automotive','Burns of 70-79% of body surface w 30-39% third degree burns',NULL),
	 ('Garden','Breakdown (mechanical) of implanted testicular prosthesis',NULL),
	 ('Automotive','Acquired night blindness',NULL),
	 ('Outdoors','Inj extn musc/fasc/tend r little finger at wrs/hnd lv, subs',NULL),
	 ('Movies','Disp fx of prox phalanx of r less toe(s), 7thK',NULL),
	 ('Industrial','Blister (nonthermal) of abdominal wall',NULL),
	 ('Electronics','Displacement of electronic bone stimulator, sequela',NULL),
	 ('Health','Pericarditis in diseases classified elsewhere',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Outdoors','Toxic effect of 2-Propanol, assault, initial encounter',NULL),
	 ('Shoes','Abrasion of penis',NULL),
	 ('Kids','Sprain of MCP joint of left index finger, sequela',NULL),
	 ('Home','Fx unsp prt of scapula, unsp shldr, subs for fx w delay heal',NULL),
	 ('Grocery','Infct of amniotic sac and membranes, unsp, second trimester',NULL),
	 ('Electronics','Oth fall from one level to another due to ice and snow, sqla',NULL),
	 ('Tools','Other circadian rhythm sleep disorder',NULL),
	 ('Shoes','Pnctr w fb of r bk wl of thorax w/o penet thor cavity, init',NULL),
	 ('Music','Mech compl of infusion catheter, subsequent encounter',NULL),
	 ('Grocery','Cocaine use, unsp with cocaine-induced anxiety disorder',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Shoes','Unsp inj unsp musc/fasc/tend at thi lev, right thigh, subs',NULL),
	 ('Sports','Corrosion of third degree of abdominal wall, subs encntr',NULL),
	 ('Clothing','Food in larynx causing other injury, initial encounter',NULL),
	 ('Toys','Idiopathic chronic gout, right ankle and foot',NULL),
	 ('Jewelry','Displ spiral fx shaft of rad, unsp arm, 7thR',NULL),
	 ('Shoes','Athscl nonbiol bypass of left leg w ulcer of heel and midft',NULL),
	 ('Health','Unspecified injury of ulnar artery at forearm level',NULL),
	 ('Beauty','Maternal exhaustion complicating labor and delivery',NULL),
	 ('Garden','Phlebitis and thombophlb of superfic vessels of l low extrem',NULL),
	 ('Garden','Oth specific joint derangements of left ankle, NEC',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Automotive','Localized vascularization of cornea, bilateral',NULL),
	 ('Books','Unspecified subluxation of unspecified patella, sequela',NULL),
	 ('Jewelry','Hemorrhage in optic nerve sheath, unspecified eye',NULL),
	 ('Health','Burn of unsp degree of left toe(s) (nail), init encntr',NULL),
	 ('Jewelry','Strain of musc/fasc/tend prt biceps, right arm, init',NULL),
	 ('Electronics','Foreign body or object entering through skin',NULL),
	 ('Shoes','Anterior sublux of proximal end of tibia, left knee, sequela',NULL),
	 ('Grocery','Nondisplaced fracture of capitate bone, right wrist, sequela',NULL),
	 ('Computers','Other specified intestinal helminthiases',NULL),
	 ('Computers','Prolonged stay in weightless environment, initial encounter',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Baby','Pathological fracture in oth disease, right hand, init',NULL),
	 ('Clothing','Open bite of unspecified ear',NULL),
	 ('Shoes','Myoneural disorder, unspecified',NULL),
	 ('Grocery','Age-rel osteopor w current path fracture, r low leg, init',NULL),
	 ('Games','Path fx in neopltc dis, unsp ulna & rad, 7thG',NULL),
	 ('Jewelry','Optic nerve hypoplasia, unspecified eye',NULL),
	 ('Jewelry','Collapsed vert, NEC, thor region, subs for fx w delay heal',NULL),
	 ('Kids','Other myositis, left forearm',NULL),
	 ('Music','Open bite of other specified part of neck, subs encntr',NULL),
	 ('Beauty','Fatigue fracture of vertebra, thoracolumbar region, init',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Pedl cyc driver inj in clsn w rail trn/veh in traf, sequela',NULL),
	 ('Health','Anaphylactic reaction due to other fish, initial encounter',NULL),
	 ('Garden','Other specified osteochondropathies, right thigh',NULL),
	 ('Baby','Insect bite (nonvenomous) of abdominal wall, init encntr',NULL),
	 ('Industrial','Other injury of rectum, sequela',NULL),
	 ('Books','Crushing injury of left lesser toe(s), subsequent encounter',NULL),
	 ('Beauty','Disp fx of lateral condyle of r tibia, 7thD',NULL),
	 ('Jewelry','Retained wood fragments',NULL),
	 ('Kids','Unsp fx head of left femur, subs for clos fx w delay heal',NULL),
	 ('Health','Nondisp fx of navicular of l foot, subs for fx w routn heal',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Hit by falling object due to acc to unpowr wtrcrft, subs',NULL),
	 ('Outdoors','Poisoning by other viral vaccines, intentional self-harm',NULL),
	 ('Clothing','Unspecified injury of plantar artery of right foot, sequela',NULL),
	 ('Baby','Superficial fb of unsp external genital organs, male',NULL),
	 ('Home','Poisoning by oth fibrin-affct drugs, self-harm, sequela',NULL),
	 ('Industrial','Adverse effect of keratolyt/keratplst/hair trmt drug, subs',NULL),
	 ('Movies','Path fx in oth disease, l humerus, subs for fx w delay heal',NULL),
	 ('Health','Exudative age-rel mclr degn, bilateral, with inactive scar',NULL),
	 ('Sports','Poisn by analeptics and opioid receptor antag, assault, subs',NULL),
	 ('Electronics','Laceration without foreign body of left elbow',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Electronics','Greenstick fx shaft of rad, r arm, subs for fx w nonunion',NULL),
	 ('Movies','Early congenital syphilis, latent',NULL),
	 ('Health','Abscess of breast associated with pregnancy, first trimester',NULL),
	 ('Books','Acute Eustachian salpingitis, right ear',NULL),
	 ('Games','Congenital absence of thigh and lower leg with foot present',NULL),
	 ('Games','Embolism due to other internal prosth dev/grft, init',NULL),
	 ('Industrial','Corrosion of first degree of right lower leg, init encntr',NULL),
	 ('Tools','Injury of urinary and pelvic organs',NULL),
	 ('Books','Oth Rh incompat react due to tranfs of bld/bld prod, sequela',NULL),
	 ('Games','Other superficial bite of unspecified knee, init encntr',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Nondisp fx of glenoid cav of scapula, unsp shldr, 7thD',NULL),
	 ('Beauty','Nondisplaced transcondylar fracture of unsp humerus, sequela',NULL),
	 ('Movies','Lacerat flexor musc/fasc/tend r rng fngr at wrs/hnd lv, init',NULL),
	 ('Movies','Adverse effect of unsp prim sys and hematolog agent, sequela',NULL),
	 ('Movies','Secondary malignant neoplasm of right lung',NULL),
	 ('Grocery','Disp fx of distal phalanx of r idx fngr, init for opn fx',NULL),
	 ('Kids','Juvenile osteochondrosis of metatarsus',NULL),
	 ('Movies','Athscl nonbiological bypass of the extremities w rest pain',NULL),
	 ('Health','Elephantiasis of left eye, unspecified eyelid',NULL),
	 ('Music','Attention-deficit hyperactivity disorder, other type',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Tools','Other specified brain damage due to birth injury',NULL),
	 ('Movies','Fall (on)(from) escalator, initial encounter',NULL),
	 ('Tools','Cellulitis of unspecified part of limb',NULL),
	 ('Music','Unsp disp fx of first cervcal vert, subs for fx w delay heal',NULL),
	 ('Garden','Postproc hematoma and seroma of the spleen fol a procedure',NULL),
	 ('Beauty','Other secondary osteonecrosis, other site',NULL),
	 ('Toys','Other fall from one level to another, subsequent encounter',NULL),
	 ('Kids','Ring or oth jewelry causing external constriction, subs',NULL),
	 ('Automotive','Contusion of unsp middle finger without damage to nail',NULL),
	 ('Clothing','Private garage of single-family (private) house as place',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Toys','Stiffness of hip, not elsewhere classified',NULL),
	 ('Movies','Oth fx upr end r rad, 7thF',NULL),
	 ('Games','Toxic effect of venom of black widow spider, assault, init',NULL),
	 ('Games','Displ seg fx shaft of l tibia, 7thQ',NULL),
	 ('Kids','Legal intervnt w inj by dynamite, law enforc offl inj, subs',NULL),
	 ('Health','Acute hepatitis B with delta-agent with hepatic coma',NULL),
	 ('Grocery','Contusion of left forearm, sequela',NULL),
	 ('Grocery','Other hyperaldosteronism',NULL),
	 ('Outdoors','Injury of femoral nrv at hip and thi lev, right leg, sequela',NULL),
	 ('Jewelry','Open bite, left knee',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Books','Nondisplaced fracture of medial malleolus of left tibia',NULL),
	 ('Baby','Malar fracture, right side, sequela',NULL),
	 ('Home','Congenital metatarsus primus varus',NULL),
	 ('Games','Blister (nonthermal) of thigh',NULL),
	 ('Jewelry','Encounter for sterilization',NULL),
	 ('Books','Corrosion of first degree of other site of trunk',NULL),
	 ('Baby','Nondisp fx of shaft of left clavicle, init for clos fx',NULL),
	 ('Grocery','Insect bite (nonvenomous) of right back wall of thorax, init',NULL),
	 ('Industrial','Accidental malfunction from oth firearms, sequela',NULL),
	 ('Clothing','Non-pressure chronic ulcer of right ankle w necrosis of bone',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Clothing','Abnormal findings on diagnostic imaging of cnsl',NULL),
	 ('Garden','Diseases of the respiratory system complicating childbirth',NULL),
	 ('Electronics','Nondisp Maisonneuve''s fx r leg, 7thN',NULL),
	 ('Automotive','Other firearm discharge, undetermined intent, subs encntr',NULL),
	 ('Toys','Partial loss of teeth, unspecified cause, class IV',NULL),
	 ('Jewelry','Nondisp suprcndl fx w intrcndl extn lower end of l femur',NULL),
	 ('Shoes','Contusion of eyeball and orbital tissues, right eye, subs',NULL),
	 ('Clothing','Unspecified injury of lung, unspecified, subs encntr',NULL),
	 ('Clothing','Corros first deg of unsp site left lower limb, except ank/ft',NULL),
	 ('Outdoors','Toxic effect of noxious substances eaten as food, acc, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Disorders of muscle in diseases classd elswhr, l low leg',NULL),
	 ('Home','Subluxation of MCP joint of right ring finger',NULL),
	 ('Tools','Path fracture in neoplastic disease, tibia and fibula',NULL),
	 ('Music','Pnctr w fb of l little finger w damage to nail, init',NULL),
	 ('Electronics','Burn of unspecified degree of left upper arm, subs encntr',NULL),
	 ('Computers','Burn of third degree of right lower leg',NULL),
	 ('Electronics','Leukemia, unspecified',NULL),
	 ('Tools','Bitten by sea lion, subsequent encounter',NULL),
	 ('Sports','Unsp traum nondisp spondylolysis of 7th cervcal vert, 7thG',NULL),
	 ('Garden','Other problems with newborn',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Bone donor, unspecified',NULL),
	 ('Books','Puncture wound w/o foreign body of unsp upper arm, init',NULL),
	 ('Shoes','Displ suprcndl fx w/o intrcndl extn low end r femr, 7thQ',NULL),
	 ('Books','Burn second degree of single r finger except thumb, init',NULL),
	 ('Tools','Corros 3rd deg mu sites of r shldr/up lmb, ex wrs/hnd, subs',NULL),
	 ('Shoes','Partial traumatic amputation of one left lesser toe',NULL),
	 ('Industrial','Major lacerat great saph at hip and thi lev, right leg, subs',NULL),
	 ('Shoes','Anterior subluxation of right ulnohumeral joint',NULL),
	 ('Computers','Underdosing of unspecified hormone antagonists, sequela',NULL),
	 ('Movies','Nondisp fx of coracoid pro, r shldr, subs for fx w nonunion',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Nondisp fx of epiphy (separation) (upper) of r femr, 7thM',NULL),
	 ('Jewelry','Infect/inflm reaction due to int fix of r humerus, sequela',NULL),
	 ('Beauty','Maternal care for fetal problem, unsp, second tri, fetus 5',NULL),
	 ('Kids','Inj cutan sensory nerve at ank/ft level, unsp leg, init',NULL),
	 ('Home','Unspecified disorder of patella, unspecified knee',NULL),
	 ('Automotive','Breakdown of carotid arterial graft (bypass), subs',NULL),
	 ('Electronics','Other secondary chronic gout, right shoulder, without tophus',NULL),
	 ('Jewelry','Oth physl fx upr end rad, unsp arm, subs for fx w delay heal',NULL),
	 ('Beauty','Distal interphalangeal psoriatic arthropathy',NULL),
	 ('Sports','Other effects of deprivation, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Unsp inj intrns musc/fasc/tend l idx fngr at wrs/hnd lv,sqla',NULL),
	 ('Jewelry','Contracture of muscle, unspecified ankle and foot',NULL),
	 ('Kids','Major laceration of unspecified external jugular vein',NULL),
	 ('Tools','Nondisp fx of 5th metatarsal bone, unsp ft, 7thP',NULL),
	 ('Automotive','Subluxation of carpometacarpal joint of left thumb, subs',NULL),
	 ('Industrial','Oth nondisp fx of 1st cervcal vert, subs for fx w routn heal',NULL),
	 ('Tools','Strain of muscle, fascia and tendon of left hip, subs encntr',NULL),
	 ('Clothing','Inj flexor musc/fasc/tend r mid finger at forearm level',NULL),
	 ('Clothing','War op w direct blast effect of nuclear weapon, civ, subs',NULL),
	 ('Games','Strain msl/tnd lng extn msl toe at ank/ft lev, r foot, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Home','Unspecified sprain of right elbow, subsequent encounter',NULL),
	 ('Movies','Burn of unspecified degree of left wrist, sequela',NULL),
	 ('Grocery','Other sickle-cell disorders without crisis',NULL),
	 ('Automotive','Other amebic genitourinary infections',NULL),
	 ('Music','Superficial foreign body, unspecified hip, subs encntr',NULL),
	 ('Garden','Drug use complicating pregnancy, unspecified trimester',NULL),
	 ('Computers','Early congenital syphilitic rhinitis',NULL),
	 ('Home','Partial traumatic amp at knee level, unsp lower leg, subs',NULL),
	 ('Beauty','Adverse effect of unspecified psychotropic drug, subs encntr',NULL),
	 ('Jewelry','Assault by unspecified explosive, initial encounter',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Tools','Partial traum amp of two or more unsp lesser toes, sequela',NULL),
	 ('Automotive','Encounter for genetic testing of male for pro mgmt',NULL),
	 ('Jewelry','Unsp inj flxr musc/fasc/tend r mid fngr at wrs/hnd lv, init',NULL),
	 ('Home','Unsp mtrcy rider inj pick-up truck, pk-up/van nontraf, subs',NULL),
	 ('Movies','Parent-biological child conflict',NULL),
	 ('Movies','Varus deformity, not elsewhere classified, right elbow',NULL),
	 ('Sports','Poisoning by amphetamines, intentional self-harm, subs',NULL),
	 ('Books','Idiopathic gout, left knee',NULL),
	 ('Automotive','Corrosion of third degree of unsp scapular region, init',NULL),
	 ('Kids','Obstructed labor due to oth malpos and malpresent, fetus 4',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Grocery','Corrosion of second degree of scapular region',NULL),
	 ('Baby','Driver of pk-up/van inj in clsn w pedl cyc nontraf, sequela',NULL),
	 ('Garden','Neonatal adrenoleukodystrophy',NULL),
	 ('Books','Sltr-haris Type II physl fx upr end humer, l arm, 7thG',NULL),
	 ('Beauty','Periprosth osteolysis of internal prosthetic joint, sequela',NULL),
	 ('Computers','Age-related reticular degeneration of retina, bilateral',NULL),
	 ('Industrial','Poisoning by rifampicins, accidental (unintentional), init',NULL),
	 ('Industrial','Mech compl of cranial or spinal infusion catheter, subs',NULL),
	 ('Home','Nondisplaced fracture of body of left talus, sequela',NULL),
	 ('Books','Dvrtclos of both sm and lg int w/o perf or abscs w/o bleed',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Attention and concentration deficit following cerebral infrc',NULL),
	 ('Music','Eclampsia complicating pregnancy, second trimester',NULL),
	 ('Automotive','Abrasion, left lower leg',NULL),
	 ('Shoes','Cerebral infrc due to embolism of middle cerebral artery',NULL),
	 ('Tools','Osteomyelitis of left orbit',NULL),
	 ('Outdoors','Path fx in oth dis, unsp humerus, subs for fx w routn heal',NULL),
	 ('Health','Major laceration of femoral artery, right leg',NULL),
	 ('Sports','Nondisplaced oblique fracture of shaft of unsp ulna, sequela',NULL),
	 ('Sports','Pedal cycle passenger injured in collision w unsp mv nontraf',NULL),
	 ('Jewelry','Laceration with foreign body of trachea, initial encounter',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Computers','Other mononeuropathies',NULL),
	 ('Jewelry','Tox eff of corrosv alkalis and alk-like substnc, undet, sqla',NULL),
	 ('Tools','Maternal care for viable fetus in abd preg, unsp tri, oth',NULL),
	 ('Industrial','Corrosion of unspecified degree of left axilla',NULL),
	 ('Automotive','Nondisp trimalleol fx unsp low leg, 7thC',NULL),
	 ('Automotive','Exposure to flames in controlled fire, not in bldg, sequela',NULL),
	 ('Baby','Pregnancy with inconclusive fetal viability, fetus 4',NULL),
	 ('Shoes','Nondisp fx of medial cuneiform of r foot, init for opn fx',NULL),
	 ('Automotive','Wedge comprsn fx second lum vert, subs for fx w routn heal',NULL),
	 ('Tools','Nondisplaced trimalleolar fracture of l low leg, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Toys','Disp fx of lateral malleolus of l fibula, 7thR',NULL),
	 ('Grocery','Oth behav/emotn disord w onset usly occur in chldhd and adol',NULL),
	 ('Health','Other specified arthritis, left elbow',NULL),
	 ('Beauty','Burn third deg of unsp site unsp lower limb, ex ank/ft, subs',NULL),
	 ('Jewelry','Atrophy of thyroid (acquired)',NULL),
	 ('Baby','Other idiopathic scoliosis, site unspecified',NULL),
	 ('Garden','Toxic effect of lead and its compounds, self-harm, sequela',NULL),
	 ('Sports','Oth fx second lum vertebra, subs for fx w routn heal',NULL),
	 ('Games','Drug-induced chronic gout, left knee, with tophus (tophi)',NULL),
	 ('Industrial','Maternal care for anti-D antibodies, unsp trimester, fetus 3',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Shoes','Child neglect or abandonment, confirmed, sequela',NULL),
	 ('Grocery','Corros 2nd deg mul sites of right low limb, ex ank/ft, sqla',NULL),
	 ('Industrial','Leakage of infusion catheter, sequela',NULL),
	 ('Movies','Complete traumatic trnsphal amputation of l rng fngr, init',NULL),
	 ('Garden','External constriction of unspecified part of head, sequela',NULL),
	 ('Computers','Disp fx of med condyle of r femur, init for opn fx type I/2',NULL),
	 ('Movies','Pneumococcal arthritis, left elbow',NULL),
	 ('Industrial','Burn of unspecified degree of right foot, initial encounter',NULL),
	 ('Baby','Pasngr in pk-up/van injured in clsn w oth mv in traf, init',NULL),
	 ('Music','Poisoning by oth synthetic narcotics, self-harm, init',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Tools','Complete traumatic amputation of l low leg, level unsp, subs',NULL),
	 ('Garden','Driver of pk-up/van inj in clsn w rail trn/veh in traf, init',NULL),
	 ('Sports','Displ intertroch fx r femr, 7thH',NULL),
	 ('Beauty','Contact with other sharp object(s), NEC, initial encounter',NULL),
	 ('Games','STEMI & NSTEMI mocard infrc',NULL),
	 ('Toys','Activity, laundry',NULL),
	 ('Automotive','Sltr-haris Type II physl fx low end l tibia, 7thG',NULL),
	 ('Garden','Non-pressure chronic ulcer of unspecified heel and midfoot',NULL),
	 ('Music','Pnctr w foreign body of thmb w/o damage to nail, init',NULL),
	 ('Tools','Laceration of unsp kidney, unspecified degree, subs encntr',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Crushing injury of unspecified wrist',NULL),
	 ('Garden','Exudative cyst of pars plana, left eye',NULL),
	 ('Industrial','Unspecified disorder of synovium and tendon, multiple sites',NULL),
	 ('Grocery','Disp fx of low epiphy (separation) of l femr, 7thB',NULL),
	 ('Books','Cataract with neovascularization, right eye',NULL),
	 ('Home','Strain flexor musc/fasc/tend unsp finger at wrs/hnd lv, init',NULL),
	 ('Automotive','Cysts of left lower eyelid',NULL),
	 ('Toys','Traumatic cerebral edema w LOC of unsp duration, init',NULL),
	 ('Tools','Laceration w/o foreign body of oth part of head, subs encntr',NULL),
	 ('Movies','Pressure ulcer of left upper back',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Jewelry','Poisoning by opth drugs and preparations, accidental, init',NULL),
	 ('Jewelry','Corrosion of second degree of left palm, initial encounter',NULL),
	 ('Electronics','Angioneurotic edema, subsequent encounter',NULL),
	 ('Jewelry','Poisoning by other opioids, undetermined',NULL),
	 ('Movies','Acute atopic conjunctivitis, bilateral',NULL),
	 ('Books','Displacement (lateral) of globe, left eye',NULL),
	 ('Shoes','Path fx in oth disease, r tibia, subs for fx w delay heal',NULL),
	 ('Outdoors','Toxic effect of harmful algae and algae toxins, acc, init',NULL),
	 ('Sports','Rheu arthritis w rheu factor of r knee w/o org/sys involv',NULL),
	 ('Garden','Zygomatic fracture, unspecified side',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Grocery','Alcoholic hepatic failure without coma',NULL),
	 ('Sports','Contact with other nonpowered hand tool, initial encounter',NULL),
	 ('Music','Pathological fracture, not elsewhere classified',NULL),
	 ('Books','Nondisp fx of body of right calcaneus, init for opn fx',NULL),
	 ('Music','Abrasion of left little finger',NULL),
	 ('Clothing','Congenital absence and hypoplasia of umbilical artery',NULL),
	 ('Home','Nondisp bicondylar fx r tibia, 7thM',NULL),
	 ('Computers','Other physeal fracture of upper end of right fibula',NULL),
	 ('Music','Sltr-haris Type II physl fx upr end humer, r arm, 7thD',NULL),
	 ('Books','Type 2 diabetes w oth diabetic ophthalmic complication',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Outdoors','Nondisp oth fx tuberosity of l calcaneus, 7thD',NULL),
	 ('Kids','Patient room in hospital as place',NULL),
	 ('Garden','Insect bite (nonvenomous) of right thumb, subs encntr',NULL),
	 ('Clothing','Other secondary gout, shoulder',NULL),
	 ('Tools','Drown due to being thrown ovrbrd by motion of passenger ship',NULL),
	 ('Beauty','Lacerat intrns musc/fasc/tend l lit fngr at wrs/hnd lv, init',NULL),
	 ('Jewelry','Person outside pk-up/van inj in clsn w rail trn/veh nontraf',NULL),
	 ('Garden','Pressure ulcer of left heel, stage 4',NULL),
	 ('Health','Nondisplaced subtrochnt fracture of right femur, sequela',NULL),
	 ('Jewelry','Myopia',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Unspecified fracture of third lumbar vertebra',NULL),
	 ('Automotive','Unsp mtrcy rider inj in clsn w rail trn/veh nontraf, init',NULL),
	 ('Shoes','Adult pulmonary Langerhans cell histiocytosis',NULL),
	 ('Books','Neoplasm of uncertain behavior of ureter',NULL),
	 ('Jewelry','Lateral dislocation of unsp ulnohumeral joint, subs encntr',NULL),
	 ('Kids','Maternal care for disproportion due to hydrocephalic fetus',NULL),
	 ('Health','Toxic effects of phenol and phenol homologues',NULL),
	 ('Music','Other specified conduction disorders',NULL),
	 ('Electronics','Mech compl of cystostomy catheter, sequela',NULL),
	 ('Movies','Displ spiral fx shaft of ulna, l arm, 7thG',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Baby','Inj deep peroneal nrv at ank/ft level, left leg, sequela',NULL),
	 ('Books','Sprain of interphalangeal joint of left ring finger',NULL),
	 ('Toys','Abrasion of right thumb, subsequent encounter',NULL),
	 ('Tools','Recurrent dislocation, unspecified joint',NULL),
	 ('Automotive','Disorder of amniotic fluid and membrns, unsp, third tri',NULL),
	 ('Grocery','Poisoning by antithyroid drugs, undetermined, sequela',NULL),
	 ('Home','Sltr-haris Type IV physl fx upr end rad, l arm, 7thG',NULL),
	 ('Health','Chronic embolism and thrombosis of subclavian vein',NULL),
	 ('Toys','Stable burst fracture of fifth lum vertebra, init for opn fx',NULL),
	 ('Books','Unspecified astigmatism, right eye',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Jewelry','War op involving unsp explosion and fragments, milt, init',NULL),
	 ('Industrial','Laceration w/o foreign body of right shoulder, subs encntr',NULL),
	 ('Books','Ulcerative (chronic) pancolitis with intestinal obstruction',NULL),
	 ('Games','Nicotine dependence, chewing tobacco, in remission',NULL),
	 ('Jewelry','Stenosis of bilateral lacrimal punctum',NULL),
	 ('Outdoors','Rupture of synovium, unspecified ankle',NULL),
	 ('Games','Laceration with foreign body of right forearm, sequela',NULL),
	 ('Baby','Unsp inj flexor musc/fasc/tend unsp fngr at forarm lv, sqla',NULL),
	 ('Tools','Driver of snowmobile injured in traffic accident, subs',NULL),
	 ('Health','Oth fx lower end of l femur, subs for clos fx w routn heal',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Superficial frostbite of ear',NULL),
	 ('Movies','Crushing injury of left wrist and hand, subsequent encounter',NULL),
	 ('Tools','Cont preg aft elctv fetl rdct of 1 fts or more,unsp tri,fts4',NULL),
	 ('Kids','Athscl native arteries of left leg w ulceration of ankle',NULL),
	 ('Music','Fall on and from ladder, sequela',NULL),
	 ('Beauty','Nondisp fx of olecran pro w/o intartic extn r ulna, 7thC',NULL),
	 ('Home','Injury of unsp blood vessel at shoulder and upper arm level',NULL),
	 ('Home','Bucket-hndl tear of medial mensc, crnt inj, unsp knee, init',NULL),
	 ('Outdoors','Struck by other birds, subsequent encounter',NULL),
	 ('Beauty','And unsp drugs aff the autonomic nervous system',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Beauty','Adverse effect of thyroid hormones and substitutes, init',NULL),
	 ('Outdoors','Cystic meniscus, unspecified meniscus, right knee',NULL),
	 ('Electronics','Background retinopathy and retinal vascular changes',NULL),
	 ('Games','Personal history of malignant neoplasm of ureter',NULL),
	 ('Automotive','Burn of third degree of left ear, subsequent encounter',NULL),
	 ('Health','Unsp injury of muscle, fascia and tendon of pelvis, subs',NULL),
	 ('Sports','Mature T/NK-cell lymphomas, unsp, intrathoracic lymph nodes',NULL),
	 ('Computers','Assault by drowning and submersion, unspecified, subs encntr',NULL),
	 ('Books','Partial traumatic amputation of right midfoot, init encntr',NULL),
	 ('Home','Osteopathy in diseases classified elsewhere, left upper arm',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Unsp inj musc/tend post grp at low leg lev, right leg, sqla',NULL),
	 ('Books','Matern care for disproprtn due to unusually large fetus, oth',NULL),
	 ('Kids','Contus/lac cereb, w LOC >24 hr w/o ret consc w surv, subs',NULL),
	 ('Shoes','Traumatic vasospastic syndrome, subsequent encounter',NULL),
	 ('Games','Laceration w foreign body of right thumb with damage to nail',NULL),
	 ('Beauty','Sprain of MCP joint of right little finger, sequela',NULL),
	 ('Music','Crushed betw inflatbl crft and oth wtrcrft/obj due to clsn',NULL),
	 ('Music','Pasngr in hv veh injured in clsn w pedl cyc nontraf, sequela',NULL),
	 ('Sports','Toxic effect of venom of tarantula, self-harm, init',NULL),
	 ('Jewelry','Path fx in oth disease, r ankle, subs for fx w routn heal',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Automotive','Acute epidemic hemorrhagic conjunctivitis (enteroviral)',NULL),
	 ('Automotive','Problems related to education and literacy',NULL),
	 ('Grocery','External constrict of unsp eyelid and periocular area, subs',NULL),
	 ('Toys','Benign neoplasm of short bones of left lower limb',NULL),
	 ('Music','Rheumatic disorders of both mitral and tricuspid valves',NULL),
	 ('Baby','Car driver injured in clsn w rail trn/veh nontraf, sequela',NULL),
	 ('Home','Car passenger injured in nonclsn transport accident nontraf',NULL),
	 ('Automotive','Burn of unsp eye and adnexa, part unspecified, init encntr',NULL),
	 ('Tools','Trichiasis without entropian left lower eyelid',NULL),
	 ('Toys','Posterior subluxation of unsp sternoclavicular joint, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Health','Pathological dislocation of unsp foot, NEC',NULL),
	 ('Grocery','Corneal ectasia, unspecified eye',NULL),
	 ('Outdoors','Nondisp spiral fx shaft of l fibula, 7thE',NULL),
	 ('Outdoors','Disord of visual cortex in neoplasm, right side of brain',NULL),
	 ('Shoes','Laceration of left Achilles tendon, sequela',NULL),
	 ('Baby','Smith''s fracture of unspecified radius, sequela',NULL),
	 ('Health','Poisoning by emetics, undetermined, sequela',NULL),
	 ('Home','Minor laceration of body of pancreas, sequela',NULL),
	 ('Toys','Burn of second degree of left thumb (nail), sequela',NULL),
	 ('Garden','Corrosion of third degree of elbow',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Grocery','Term delivery with preterm labor, second trimester, fetus 1',NULL),
	 ('Books','Anaphylactic reaction due to eggs, initial encounter',NULL),
	 ('Shoes','Oth fx unsp femur, subs for opn fx type 3A/B/C w nonunion',NULL),
	 ('Baby','Occ of anml-drn vehicle injured in clsn w ped/anml, sequela',NULL),
	 ('Clothing','Displ oblique fx shaft of unsp tibia, 7thD',NULL),
	 ('Electronics','Term delivery with preterm labor, second trimester, fetus 1',NULL),
	 ('Beauty','Toxic effect of fluorine gas and hydrogen fluoride, slf-hrm',NULL),
	 ('Home','Iliotibial band syndrome',NULL),
	 ('Tools','Dislocation of MCP joint of left middle finger, subs',NULL),
	 ('Industrial','Nondisp fx of nk of 2nd MC bone, r hand, 7thK',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Electronics','Other chondrocalcinosis, hand',NULL),
	 ('Clothing','Explosn of bomb placed during war op but expld after, milt',NULL),
	 ('Clothing','Occlusion and stenosis of middle cerebral artery',NULL),
	 ('Grocery','Genital varices in pregnancy',NULL),
	 ('Toys','Unsp fx shaft of left radius, subs for clos fx w nonunion',NULL),
	 ('Beauty','Nondisp transverse fx shaft of unsp rad, 7thJ',NULL),
	 ('Beauty','Sezary disease, extranodal and solid organ sites',NULL),
	 ('Outdoors','Pedl cyc pasngr inj in clsn w statnry object nontraf, sqla',NULL),
	 ('Tools','Contact with hot drinks, subsequent encounter',NULL),
	 ('Baby','Other secondary chronic gout, left hip, without tophus',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Shoes','Oth fx first MC bone, unsp hand, subs for fx w delay heal',NULL),
	 ('Electronics','Encounter for aftercare following liver transplant',NULL),
	 ('Outdoors','Transient visual loss, right eye',NULL),
	 ('Grocery','Acquired stenosis of right external ear canal, unspecified',NULL),
	 ('Sports','Adverse effect of other viral vaccines, subsequent encounter',NULL),
	 ('Baby','Other osteonecrosis, right shoulder',NULL),
	 ('Outdoors','Rolando''s fracture',NULL),
	 ('Books','Pre-exist hyp heart and chr kidney disease comp the puerp',NULL),
	 ('Automotive','Person injured wh brd/alit from dune buggy, init',NULL),
	 ('Baby','Benign neoplasm of cornea',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Computers','Laceration without foreign body, right knee, subs encntr',NULL),
	 ('Health','Spondylolisthesis, sacral and sacrococcygeal region',NULL),
	 ('Automotive','Other dislocation of right knee, sequela',NULL),
	 ('Clothing','Adverse effect of systemic anti-infect/parasit, subs',NULL),
	 ('Outdoors','Athscl unsp type bypass graft(s) of extremity w ulceration',NULL),
	 ('Tools','Fall (on) (from) unspecified stairs and steps, subs encntr',NULL),
	 ('Baby','Lacerat flexor musc/fasc/tend l thm at forarm lv, sequela',NULL),
	 ('Baby','Malignant neoplasm of anterior wall of bladder',NULL),
	 ('Games','Oth medical procedures cause abn react/compl, w/o misadvnt',NULL),
	 ('Outdoors','Strike/struck by front passenger side auto airbag, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Books','Oth traum displ spondylolysis of 4th cervcal vert, 7thG',NULL),
	 ('Movies','Fracture of xiphoid process, sequela',NULL),
	 ('Toys','Spontaneous rupture of flexor tendons, left ankle and foot',NULL),
	 ('Beauty','Corrosion of first degree of unspecified elbow',NULL),
	 ('Beauty','Nondisp fx of shaft of unsp clavicle, subs for fx w nonunion',NULL),
	 ('Industrial','Fracture of vault of skull, subs for fx w delay heal',NULL),
	 ('Home','Oth rheumatoid arthritis with rheumatoid factor of unsp hand',NULL),
	 ('Books','Nondisp fx of head of r rad, 7thJ',NULL),
	 ('Music','Personal history of military deployment',NULL),
	 ('Books','Complicated cataract',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Obst due to fb acc left in body fol inject or immuniz, init',NULL),
	 ('Jewelry','Chronic angle-closure glaucoma, left eye, stage unspecified',NULL),
	 ('Jewelry','Sltr-haris Type II physl fx upper end humer, unsp arm, sqla',NULL),
	 ('Clothing','Diuretics and oth and unsp drug/meds/biol subst',NULL),
	 ('Automotive','Unsp superficial injury of unspecified forearm, init encntr',NULL),
	 ('Outdoors','Other foreign object in larynx causing asphyxiation',NULL),
	 ('Toys','Torus fx lower end of unsp femur, subs for fx w delay heal',NULL),
	 ('Toys','Stress fracture, right fibula',NULL),
	 ('Beauty','Peptic ulcer of newborn',NULL),
	 ('Electronics','Other spondylopathies',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Exudative age-related macular degeneration',NULL),
	 ('Books','Unsp fx head of right femur, init for opn fx type I/2',NULL),
	 ('Books','Non-prs chronic ulcer oth prt right foot w unsp severity',NULL),
	 ('Automotive','Oth injury of unsp blood vessel at forearm level, left arm',NULL),
	 ('Grocery','Frostbite with tissue necrosis of left arm, init encntr',NULL),
	 ('Jewelry','Nondisp spiral fx shaft of unsp tibia, 7thR',NULL),
	 ('Sports','Major laceration of abdominal aorta, initial encounter',NULL),
	 ('Movies','Infect/inflm reaction due to int fix of unsp site, init',NULL),
	 ('Garden','Oth injury of vein at forearm level, unspecified arm',NULL),
	 ('Beauty','Breakdown of int fix of bones of foot and toes, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Disp fx of shaft of 5th MC bone, r hand, 7thK',NULL),
	 ('Baby','Exposure to electric transmission lines, initial encounter',NULL),
	 ('Clothing','Assault by crashing of motor vehicle',NULL),
	 ('Grocery','Epidur hemor w LOC w death due to oth causes bf consc, init',NULL),
	 ('Toys','Inj conjunctiva and corneal abrasion w/o fb, left eye, init',NULL),
	 ('Jewelry','Pnctr of abd wall w/o fb, l low q w/o penet perit cav, init',NULL),
	 ('Movies','Lac w fb of unsp front wall of thrx w/o penet thor cav, subs',NULL),
	 ('Books','Inj extn musc/fasc/tend l little finger at wrs/hnd lv, init',NULL),
	 ('Sports','Laceration w/o foreign body of right cheek and TMJ area',NULL),
	 ('Tools','Nondisp fx of olecran pro w/o intartic extn unsp ulna, 7thN',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Shoes','Toxic effect of manganese and its compounds, self-harm, init',NULL),
	 ('Baby','Unsp fx head of unsp femr, 7thH',NULL),
	 ('Tools','Other sprain of right elbow, sequela',NULL),
	 ('Beauty','Cerebral infrc due to embolism of posterior cerebral artery',NULL),
	 ('Grocery','Laceration with foreign body of left shoulder, subs encntr',NULL),
	 ('Home','Laceration without foreign body of lower leg',NULL),
	 ('Computers','Breakdown (mechanical) of cardiac pulse generator (battery)',NULL),
	 ('Toys','Personal history of dysplasia of the female genital tract',NULL),
	 ('Movies','Laceration with foreign body, right knee, initial encounter',NULL),
	 ('Health','Serous detachment of retinal pigment epithelium',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Books','Other complications of bone graft',NULL),
	 ('Tools','Hypoplastic right heart syndrome',NULL),
	 ('Home','Toxic effect of trichloroethylene, self-harm, init',NULL),
	 ('Grocery','Nondisp fx of lateral condyle of r femr, 7thP',NULL),
	 ('Sports','Disp fx of shaft of 2nd MC bone, r hand, 7thK',NULL),
	 ('Grocery','Nondisp fx of coracoid process, right shoulder, sequela',NULL),
	 ('Toys','Other shoulder lesions',NULL),
	 ('Electronics','Disp fx of right tibial spine, subs for clos fx w routn heal',NULL),
	 ('Automotive','Terrorism involving chemical weapons',NULL),
	 ('Garden','Strain intrns musc/fasc/tend r lit fngr at wrs/hnd lv, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Computers','Exposure to ignition of plastic jewelry',NULL),
	 ('Tools','Major laceration of femoral artery, right leg, init encntr',NULL),
	 ('Electronics','Poisoning by oth systemic anti-infect/parasit, assault, subs',NULL),
	 ('Kids','Puncture wound with foreign body of left wrist, subs encntr',NULL),
	 ('Clothing','Burn of first degree of back of unspecified hand, sequela',NULL),
	 ('Music','Burn of unsp degree of unspecified forearm, init encntr',NULL),
	 ('Garden','Insect bite (nonvenomous) of left index finger, subs encntr',NULL),
	 ('Games','Contusion of other part of colon, initial encounter',NULL),
	 ('Clothing','Major depressive disorder, single episode, unspecified',NULL),
	 ('Clothing','Calcium deposit in bursa, unspecified hip',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Torus fracture of upper end of unspecified ulna, sequela',NULL),
	 ('Sports','Unspecified injury of bronchus, bilateral, initial encounter',NULL),
	 ('Sports','Disp fx of base of 4th MC bone, l hand, 7thP',NULL),
	 ('Computers','Adverse effect of other general anesthetics',NULL),
	 ('Health','4-part fx surgical neck of l humerus, subs for fx w malunion',NULL),
	 ('Toys','Drvr of 3-whl mv inj in clsn w statnry object nontraf, subs',NULL),
	 ('Industrial','Nodular corneal degeneration, left eye',NULL),
	 ('Sports','Follicular lymphoma grade II, spleen',NULL),
	 ('Books','Laceration w foreign body of unsp part of head, subs encntr',NULL),
	 ('Electronics','Postproc hematoma of an endo sys org fol an endo sys proc',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Unspecified fracture of shaft of radius',NULL),
	 ('Outdoors','Unsp intracap fx unsp femr, 7thM',NULL),
	 ('Outdoors','Primary cutaneous CD30-positive T-cell proliferations',NULL),
	 ('Garden','Intentional self-harm by other hot objects, sequela',NULL),
	 ('Grocery','Lacerat blood vessels at lower leg level, right leg, subs',NULL),
	 ('Jewelry','Frostbite with tissue necrosis of left arm, sequela',NULL),
	 ('Clothing','Other bipolar disorder',NULL),
	 ('Books','Stress fracture, right foot, sequela',NULL),
	 ('Outdoors','Activity, oth involving climbing, rappelling and jumping off',NULL),
	 ('Automotive','Unspecified benign mammary dysplasia of right breast',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Coloboma of iris',NULL),
	 ('Books','Traum rupt of volar plate of l lit fngr at MCP/IP jt, sqla',NULL),
	 ('Toys','Hydroxyapatite deposition disease, left shoulder',NULL),
	 ('Kids','Toxic eff of fluorine gas and hydrogen fluoride, asslt, sqla',NULL),
	 ('Garden','Disp fx of distal phalanx of right lesser toe(s), sequela',NULL),
	 ('Electronics','Explosn of bomb placed during war op but expld after, civ',NULL),
	 ('Books','Displ transverse fx shaft of l femr, 7thQ',NULL),
	 ('Garden','Burn of unspecified degree of unspecified elbow, subs encntr',NULL),
	 ('Jewelry','Toxic effect of venom of oth reptiles, assault, subs encntr',NULL),
	 ('Games','Breakdown (mechanical) of muscle and tendon graft',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Cytomegaloviral disease, unspecified',NULL),
	 ('Computers','Encounter for oth general cnsl and advice on procreation',NULL),
	 ('Automotive','Other primary thrombocytopenia',NULL),
	 ('Music','Toxic effect of mycotoxin food contamnt, self-harm, sequela',NULL),
	 ('Books','Toxic effect of other organic solvents, assault',NULL),
	 ('Home','Prsnl hx of malig neoplm of rectum, rectosig junct, and anus',NULL),
	 ('Automotive','Cont preg aft uterin dth of one fts or more, unsp tri, fts1',NULL),
	 ('Clothing','Injury of digital nerve of right little finger, subs encntr',NULL),
	 ('Electronics','Other endophthalmitis',NULL),
	 ('Sports','Sprain of interphalangeal joint of unsp thumb, init encntr',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Garden','Inj intrinsic msl/tnd at ank/ft level, right foot, init',NULL),
	 ('Automotive','Displ transverse fx shaft of unsp ulna, 7thR',NULL),
	 ('Electronics','Poisoning by oth systemic antibiotics, undetermined, init',NULL),
	 ('Grocery','Open wound of back wall of thorax w/o penet thoracic cavity',NULL),
	 ('Tools','Oth disrd of amniotic fluid and membrns, second tri, fetus 5',NULL),
	 ('Health','Adverse effect of unsp antieplptc and sed-hypntc drugs, subs',NULL),
	 ('Clothing','Body mass index (BMI) 19 or less, adult',NULL),
	 ('Baby','Chronic osteomyelit w draining sinus, right tibia and fibula',NULL),
	 ('Computers','Other specified fever',NULL),
	 ('Industrial','Poisoning by oth drugs acting on muscles, self-harm',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Shoes','Oth superfic bite of unsp eyelid and perioculr area, sequela',NULL),
	 ('Music','Injury of visual cortex, right eye, initial encounter',NULL),
	 ('Kids','Nondisp fx of med wall of l acetab, subs for fx w delay heal',NULL),
	 ('Grocery','Fracture of left shoulder girdle, part unsp, init for opn fx',NULL),
	 ('Grocery','Abscess of tendon sheath, right shoulder',NULL),
	 ('Kids','Partial traumatic amputation of left breast, init encntr',NULL),
	 ('Home','Macular keratitis, right eye',NULL),
	 ('Jewelry','Traumatic rupture of collateral ligament of r wrist, init',NULL),
	 ('Music','Motor neuron disease, unspecified',NULL),
	 ('Grocery','Burn of first degree of forehead and cheek, init encntr',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Clothing','Glaucoma secondary to oth eye disord, left eye, mild stage',NULL),
	 ('Shoes','Nondisp fx of lateral condyle of r femr, 7thG',NULL),
	 ('Industrial','Other displaced fracture of third cervical vertebra, sequela',NULL),
	 ('Automotive','Other dislocation of unspecified foot, initial encounter',NULL),
	 ('Electronics','Alcohol use complicating pregnancy, second trimester',NULL),
	 ('Jewelry','Nondisp seg fx shaft of l tibia, 7thM',NULL),
	 ('Home','Toxic effect of tobacco cigarettes, undetermined',NULL),
	 ('Music','Oth diab with prolif diabetic rtnop with comb detach, r eye',NULL),
	 ('Health','Oth chronic hematogenous osteomyelitis, right ankle and foot',NULL),
	 ('Tools','Incomplete lesion of L4 level of lumbar spinal cord, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Tools','Iliac crest spur, unspecified hip',NULL),
	 ('Books','Cerebral infrc due to embolism of left ant cerebral artery',NULL),
	 ('Home','Other zoonotic bacterial diseases, not elsewhere classified',NULL),
	 ('Books','Disp fx of mid 3rd of navic bone of unsp wrs, 7thD',NULL),
	 ('Books','Lesion of plantar nerve, left lower limb',NULL),
	 ('Tools','Cont preg aft elctv fetl rdct of 1 fts or more,1st tri, fts5',NULL),
	 ('Automotive','Papyraceous fetus, second trimester',NULL),
	 ('Jewelry','Diffuse traumatic brain injury without loss of consciousness',NULL),
	 ('Books','Disp fx of med condyle of l femr, 7thK',NULL),
	 ('Books','Corros unsp deg mult left fingers (nail), including thumb',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Proc/trtmt not carried out because of contraindication',NULL),
	 ('Industrial','3-part fx surgical neck of r humerus, init for opn fx',NULL),
	 ('Health','Oth fx shaft of rad, r arm, 7thR',NULL),
	 ('Games','Traumatic rupture of left ear drum, sequela',NULL),
	 ('Books','Commercial fixed-wing aircraft crash injuring occupant',NULL),
	 ('Music','Other superficial bite of left upper arm',NULL),
	 ('Outdoors','Chronic gout due to renal impairment, right hand, w/o tophus',NULL),
	 ('Health','Coma scale, best verb, confused conversation, in the field',NULL),
	 ('Electronics','Displacement of int fix of right femur, sequela',NULL),
	 ('Beauty','Cnsl complications of anesthesia during pregnancy',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Garden','Unspecified fracture of unspecified wrist and hand',NULL),
	 ('Home','Erectile dysfunction following radical cystectomy',NULL),
	 ('Games','Mature B-cell leukemia Burkitt-type, in relapse',NULL),
	 ('Beauty','Cont preg aft elctv fetl rdct of 1 fts or more,unsp tri,fts4',NULL),
	 ('Beauty','Laceration of blood vessel of unspecified thumb, init encntr',NULL),
	 ('Clothing','Drug-induced chronic gout, left hand, without tophus (tophi)',NULL),
	 ('Clothing','External constriction of left shoulder, sequela',NULL),
	 ('Movies','Oth disrd of ear in diseases classified elsewhere',NULL),
	 ('Home','Maternal care for excessive fetal growth',NULL),
	 ('Outdoors','Incomplete atypical femoral fracture, right leg, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Contus/lac r cereb w LOC >24 hr w/o ret consc w surv, init',NULL),
	 ('Health','Other fracture of second metacarpal bone, right hand',NULL),
	 ('Movies','Postproc hemor of an endo sys org following other procedure',NULL),
	 ('Books','War operations involving oth conventional warfare, civilian',NULL),
	 ('Sports','Maternal care for excess fetal growth, second tri, fetus 2',NULL),
	 ('Electronics','Obstructed labor due to other abnormalities of fetus',NULL),
	 ('Industrial','Other synovitis and tenosynovitis, right hand',NULL),
	 ('Grocery','Nondisp unsp condyle fx low end r femr, 7thH',NULL),
	 ('Movies','Major laceration of superior mesenteric artery, subs encntr',NULL),
	 ('Shoes','Brucellosis due to Brucella melitensis',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Outdoors','Pedestrian injured in collision w 2/3-whl mv, unsp',NULL),
	 ('Toys','Adverse effect of propionic acid derivatives, subs encntr',NULL),
	 ('Jewelry','Unspecified superficial injury of right hand, sequela',NULL),
	 ('Health','Oth injury of unspecified Achilles tendon, sequela',NULL),
	 ('Tools','Burn of unspecified eyelid and periocular area, sequela',NULL),
	 ('Jewelry','Pain in right knee',NULL),
	 ('Tools','Benign neoplasm of connctv/soft tiss of trunk, unsp',NULL),
	 ('Industrial','Toxic eff of fluorine gas and hydrogen fluoride, undet, subs',NULL),
	 ('Automotive','Poisoning by anterior pituitary hormones, accidental, init',NULL),
	 ('Beauty','Strain extn musc/fasc/tend fngr,unsp fngr at forarm lv, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Sublux of distal interphaln joint of r idx fngr, sequela',NULL),
	 ('Health','Bucket-handle tear of lateral meniscus, current injury',NULL),
	 ('Shoes','Oth fracture of shaft of right humerus, init for clos fx',NULL),
	 ('Outdoors','Peripheral opacity of cornea, left eye',NULL),
	 ('Automotive','Traumatic rupture of cervical intervertebral disc, subs',NULL),
	 ('Toys','Nondisp fx of base of fifth metacarpal bone. left hand',NULL),
	 ('Automotive','Other congenital malformations of peripheral vascular system',NULL),
	 ('Outdoors','Unsp fracture of T9-T10 vertebra, subs for fx w routn heal',NULL),
	 ('Toys','Jump/div from boat striking surfc causing oth injury, subs',NULL),
	 ('Shoes','Unspecified superficial injury of unspecified ear, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Health','Displacement of muscle and tendon graft',NULL),
	 ('Electronics','External constriction of unsp back wall of thorax, sequela',NULL),
	 ('Baby','NIHSS score 10',NULL),
	 ('Shoes','Puncture wound with foreign body of left hand, subs encntr',NULL),
	 ('Kids','Unsp injury of left wrist, hand and finger(s), sequela',NULL),
	 ('Games','Inj ulnar artery at forearm level, right arm, subs encntr',NULL),
	 ('Electronics','Nondisp seg fx shaft of r femr, 7thD',NULL),
	 ('Garden','Displ spiral fx shaft of l femr, 7thR',NULL),
	 ('Grocery','Poisn by oth agents prim acting on the resp sys, undet, init',NULL),
	 ('Beauty','Pauciarticular juvenile rheumatoid arthritis, shoulder',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Movies','Bitten by duck, initial encounter',NULL),
	 ('Home','Inj flexor musc/fasc/tend unsp finger at wrs/hnd lv',NULL),
	 ('Industrial','External constriction, right hip, initial encounter',NULL),
	 ('Garden','Calculus of bile duct w chronic cholecystitis w obstruction',NULL),
	 ('Electronics','Other diseases of salivary glands',NULL),
	 ('Shoes','Oth parlyt syndrome fol cerebral infrc aff left nondom side',NULL),
	 ('Industrial','Disp fx of base of 3rd MC bone, l hand, 7thG',NULL),
	 ('Toys','Insect bite (nonvenomous) of scalp',NULL),
	 ('Music','Oth injury of deep palmar arch of right hand, init encntr',NULL),
	 ('Outdoors','Disp fx of epiphy (separation) (upper) of r femr, 7thQ',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Dining room in mobile home as place',NULL),
	 ('Jewelry','Greenstick fx shaft of rad, l arm, subs for fx w routn heal',NULL),
	 ('Movies','Skin transplant status',NULL),
	 ('Grocery','Toxic effect of mycotoxin food contamnt, accidental, init',NULL),
	 ('Movies','Superficial foreign body, right lower leg, sequela',NULL),
	 ('Jewelry','Whooping cough',NULL),
	 ('Clothing','Other hereditary and idiopathic neuropathies',NULL),
	 ('Toys','Minor laceration of vertebral artery',NULL),
	 ('Home','Disp fx of shaft of 2nd MC bone, r hand, 7thG',NULL),
	 ('Health','Oophoritis, unspecified',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Books','Superficial foreign body, left thigh, sequela',NULL),
	 ('Computers','Other physeal fracture of right calcaneus, sequela',NULL),
	 ('Books','Pnctr w/o fb of unsp external genital organs, male, subs',NULL),
	 ('Movies','Unsp fx l forearm, subs for opn fx type I/2 w malunion',NULL),
	 ('Games','Corros second degree of single l finger except thumb, subs',NULL),
	 ('Clothing','Oth contact with oth nonvenomous marine animals, init encntr',NULL),
	 ('Health','Oth behav/emotn disord w onset usly occur in chldhd and adol',NULL),
	 ('Games','Oth osteopor w crnt path fx, r low leg, 7thK',NULL),
	 ('Tools','Juvenile arthritis, unspecified, ankle and foot',NULL),
	 ('Books','Occup of 3-whl mv injured in nonclsn trnsp acc nontraf, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Electronics','Partial traumatic MCP amputation of left little finger, init',NULL),
	 ('Automotive','Adverse effect of iron and its compounds',NULL),
	 ('Kids','Sedative, hypnotic or anxiolytic-related use, unspecified',NULL),
	 ('Outdoors','Prsn brd/alit from bus injured pick-up truck, pk-up/van',NULL),
	 ('Outdoors','Karyotype 47, XYY',NULL),
	 ('Movies','Nondisplaced spiral fracture of shaft of ulna, left arm',NULL),
	 ('Sports','Child psychological abuse, suspected, initial encounter',NULL),
	 ('Music','Contus/lac right cerebrum w LOC >24 hr w ret consc lev, init',NULL),
	 ('Computers','Strain flexor musc/fasc/tend r mid fngr at wrs/hnd lv, init',NULL),
	 ('Health','Poisoning by antihyperlip and antiarterio drugs, self-harm',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Jewelry','Toxic effect of lacrimogenic gas, assault',NULL),
	 ('Clothing','Oth fracture of left acetabulum, init for opn fx',NULL),
	 ('Tools','Oth disorders of bone development and growth, multiple sites',NULL),
	 ('Computers','Unspecified open wound, right lower leg, subs encntr',NULL),
	 ('Jewelry','Poisoning by antithyroid drugs, assault, sequela',NULL),
	 ('Books','Disp fx of lateral end of l clavicle, subs for fx w nonunion',NULL),
	 ('Music','Injury of optic tract and pathways, right eye',NULL),
	 ('Electronics','Contusion of penis, initial encounter',NULL),
	 ('Shoes','Congenital malformation of anterior segment of eye, unsp',NULL),
	 ('Movies','Other dislocation of unspecified ulnohumeral joint',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Spondylolysis, sacral and sacrococcygeal region',NULL),
	 ('Home','Unsp injury of muscle, fascia and tendon of left hip, init',NULL),
	 ('Toys','Angioneurotic edema, initial encounter',NULL),
	 ('Sports','Pedl cyclst (driver) injured in oth transport accidents',NULL),
	 ('Electronics','Dislocation of proximal interphalangeal joint of thmb, subs',NULL),
	 ('Garden','Rheu arthritis w rheu factor of r knee w/o org/sys involv',NULL),
	 ('Games','Disp fx of olecran pro w/o intartic extn l ulna, 7thJ',NULL),
	 ('Outdoors','Oth disorders of external ear in diseases classd elswhr',NULL),
	 ('Automotive','Fibrosis due to vascular prosth dev/grft, sequela',NULL),
	 ('Electronics','Lac w fb of unsp bk wl of thorax w penet thor cavity, init',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Unspecified open wound, right foot, sequela',NULL),
	 ('Music','Mech compl of implanted penile prosthesis, initial encounter',NULL),
	 ('Computers','Bucket-hndl tear of unsp mensc, crnt injury, unsp knee, subs',NULL),
	 ('Kids','Glaucoma secondary to eye inflam, unsp eye, severe stage',NULL),
	 ('Tools','Displacement of prosthetic orbit of left eye, init encntr',NULL),
	 ('Beauty','Nondisp apophyseal fx l femr, 7thR',NULL),
	 ('Outdoors','Disp fx of med condyle of l tibia, 7thK',NULL),
	 ('Clothing','Nondisp fx of med malleolus of unsp tibia, 7thH',NULL),
	 ('Electronics','Injury of unsp nerve at lower leg level, left leg, init',NULL),
	 ('Grocery','Toxic effect of contact w oth jellyfish, accidental, subs',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Health','Nondisp bimalleol fx l low leg, 7thE',NULL),
	 ('Movies','Displaced transverse fx shaft of humerus, unsp arm, sequela',NULL),
	 ('Computers','Driver of 3-whl mv inj pk-up truck, pk-up/van in traf, init',NULL),
	 ('Electronics','Inj great saphenous at hip and thigh level, right leg, init',NULL),
	 ('Computers','Dislocation of sacroiliac and sacrococcygeal joint, subs',NULL),
	 ('Computers','Sltr-haris Type III physl fx low end humer, right arm, init',NULL),
	 ('Clothing','Contusion of oral cavity, sequela',NULL),
	 ('Beauty','Secondary infectious iridocyclitis, left eye',NULL),
	 ('Tools','Unspecified dementia with behavioral disturbance',NULL),
	 ('Health','Oth disrd of amniotic fluid and membrns, second tri, fetus 4',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Home','Abrasion of left thumb, initial encounter',NULL),
	 ('Music','Disp fx of capitate bone, right wrist, init for clos fx',NULL),
	 ('Kids','Unspecified physeal fracture of upper end of fibula',NULL),
	 ('Toys','Unsp fx shaft of unsp radius, init for opn fx type 3A/B/C',NULL),
	 ('Home','Burn of first degree of chin, sequela',NULL),
	 ('Tools','Cerebral infarction due to embolism of left carotid artery',NULL),
	 ('Kids','Adverse effect of other antiprotozoal drugs',NULL),
	 ('Games','Poisoning by benzodiazepines, accidental, init',NULL),
	 ('Movies','Oth physeal fracture of upper end of right tibia, init',NULL),
	 ('Electronics','Arterial embolism and thrombosis',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Other superficial bite of scrotum and testes',NULL),
	 ('Electronics','Terrorism, secondary effects, civilian injured, init encntr',NULL),
	 ('Baby','Underdosing of saline and osmotic laxatives',NULL),
	 ('Industrial','Unsp inj extensor musc/fasc/tend r rng fngr at wrs/hnd lv',NULL),
	 ('Tools','Intraop hemor/hemtom of a GU sys org comp a procedure',NULL),
	 ('Sports','Corrosion of third degree of unspecified thumb (nail)',NULL),
	 ('Beauty','Longitudinal reduction defect of ulna',NULL),
	 ('Shoes','Poisoning by unspecified antidepressants, assault',NULL),
	 ('Industrial','Congenital diverticulum of esophagus',NULL),
	 ('Health','Nondisp seg fx shaft of r femur, init for opn fx type 3A/B/C',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Grocery','Mtrcy driver injured in collision w nonmtr vehicle nontraf',NULL),
	 ('Jewelry','Postpartum thyroiditis',NULL),
	 ('Industrial','Osseous stenosis of neural canal of lower extremity',NULL),
	 ('Home','Displaced apophyseal fx unsp femur, init for opn fx type I/2',NULL),
	 ('Sports','Unstable burst fracture of second thoracic vertebra, init',NULL),
	 ('Garden','Poisoning by antiasthmatics, assault, subsequent encounter',NULL),
	 ('Automotive','Adverse effect of other general anesthetics, sequela',NULL),
	 ('Jewelry','Failed or difficult intubation',NULL),
	 ('Sports','Other superficial bite of right little finger, sequela',NULL),
	 ('Kids','Contact with fats and cooking oils, subsequent encounter',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Jewelry','Oth fracture of unsp ilium, subs for fx w routn heal',NULL),
	 ('Health','Rheumatoid bursitis, hip',NULL),
	 ('Toys','Assault by smoke, fire and flames, sequela',NULL),
	 ('Tools','Toxic effect of sulfur dioxide, assault, subs encntr',NULL),
	 ('Baby','Oth fx upr end r rad, subs for opn fx type 3A/B/C w malunion',NULL),
	 ('Sports','Inj right quadriceps muscle, fascia and tendon, sequela',NULL),
	 ('Health','Disp fx of greater trochanter of r femr, 7thJ',NULL),
	 ('Automotive','Pnctr w/o fb of right lesser toe(s) w damage to nail, init',NULL),
	 ('Home','Intraop hemor/hemtom of a resp sys org comp a procedure',NULL),
	 ('Garden','Unspecified viral encephalitis',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Laceration with foreign body of right upper arm, sequela',NULL),
	 ('Clothing','Drown due to fall off canoe or kayak, sequela',NULL),
	 ('Outdoors','Non-pressure chronic ulcer of thigh',NULL),
	 ('Toys','Poisoning by glucocort/synth analog, assault',NULL),
	 ('Outdoors','Adverse effect of appetite depressants, initial encounter',NULL),
	 ('Garden','Unsp injury of blood vessels at wrs/hnd lv of left arm, init',NULL),
	 ('Computers','Burn of third degree of unspecified toe(s) (nail), sequela',NULL),
	 ('Electronics','Nondisp transverse fx shaft of l fibula, 7thG',NULL),
	 ('Outdoors','Sltr-haris Type II physeal fx unspecified metatarsal, init',NULL),
	 ('Outdoors','Glaucomatous flecks (subcapsular), right eye',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Torus fracture of upper end of right tibia',NULL),
	 ('Books','Burns of 60-69% of body surface w 40-49% third degree burns',NULL),
	 ('Outdoors','Other birth injuries to scalp',NULL),
	 ('Shoes','Toxic effect of other seafood, assault, subsequent encounter',NULL),
	 ('Toys','Disp fx of head of r radius, subs for clos fx w delay heal',NULL),
	 ('Jewelry','Accidental twist by another person, initial encounter',NULL),
	 ('Home','Poisoning by keratolyt/keratplst/hair trmt drug, self-harm',NULL),
	 ('Health','Inj adductor musc/fasc/tend left thigh, sequela',NULL),
	 ('Tools','Maternal care for excessive fetal growth',NULL),
	 ('Toys','Fracture of body of sternum, subs for fx w routn heal',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Clothing','Fx unsp prt of nk of l femr, 7thH',NULL),
	 ('Jewelry','Unspecified malignant neoplasm of skin, unspecified',NULL),
	 ('Games','Oth intartic fx lower end r rad, subs for clos fx w nonunion',NULL),
	 ('Home','Toxic effect of homologues of benzene, assault',NULL),
	 ('Clothing','Displ artic fx head of unsp femur, init for opn fx type I/2',NULL),
	 ('Automotive','Legal intervnt w injury by rubr bulet, bystand injured',NULL),
	 ('Toys','Toxic effect of manganese and its compounds, undetermined',NULL),
	 ('Tools','War operations involving explosion of marine mine',NULL),
	 ('Health','Arthropathies in oth diseases classd elswhr, left ank/ft',NULL),
	 ('Shoes','Personal history of congenital malform of face and neck',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Displ commnt fx unsp patella, subs for clos fx w malunion',NULL),
	 ('Games','Unsp inj unsp blood vess at hip and thi lev, unsp leg, subs',NULL),
	 ('Sports','Ped on sktbrd injured in collision w pedl cyc nontraf, subs',NULL),
	 ('Clothing','Oth fracture of unsp lower leg, subs for clos fx w nonunion',NULL),
	 ('Computers','Folliculitis ulerythematosa reticulata',NULL),
	 ('Toys','Unspecified dislocation of right ring finger, sequela',NULL),
	 ('Health','Tidal wave due to landslide, subsequent encounter',NULL),
	 ('Sports','Other sites of candidiasis',NULL),
	 ('Games','Disp fx of trapezium, left wrist, subs for fx w malunion',NULL),
	 ('Tools','Nondisplaced oblique fracture of shaft of left ulna, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Kids','Activity, springboard and platform diving',NULL),
	 ('Industrial','Unsp injury of musc/fasc/tend triceps, right arm, sequela',NULL),
	 ('Grocery','Assault by airgun discharge, sequela',NULL),
	 ('Games','Oth fx shaft of l tibia, 7thN',NULL),
	 ('Toys','Displ midcervical fx unsp femur, init for opn fx type I/2',NULL),
	 ('Automotive','Nondisplaced oblique fracture of shaft of unspecified ulna',NULL),
	 ('Electronics','Poisoning by other laxatives, undetermined, init encntr',NULL),
	 ('Sports','Toxic effect of chlorofluorocarbons, intentional self-harm',NULL),
	 ('Home','Corrosion of first degree of right palm, sequela',NULL),
	 ('Health','Car occupant (driver) injured in unsp traf, sequela',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Beauty','Oth stimulant use, unsp with unsp stimulant-induced disorder',NULL),
	 ('Grocery','Sprain of tibiofibular ligament of right ankle',NULL),
	 ('Automotive','Complete traumatic amputation at right hip joint, subs',NULL),
	 ('Computers','Pnctr w/o fb of abd wall, unsp quadrant w penet perit cav',NULL),
	 ('Health','Strain of flexor musc/fasc/tend l thm at forarm lv, sequela',NULL),
	 ('Sports','Poisn by unsp sys anti-infect and antiparastc, slf-hrm, subs',NULL),
	 ('Tools','Chronic angle-closure glaucoma, bilateral, mild stage',NULL),
	 ('Movies','Kearns-Sayre syndrome',NULL),
	 ('Tools','Oth serum reaction due to admin blood/products, sequela',NULL),
	 ('Electronics','Oth parlyt synd fol oth ntrm intcrn hemor aff right dom side',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Sports','Displaced unsp fracture of unspecified great toe, sequela',NULL),
	 ('Music','Strain extn musc/fasc/tend r idx fngr at wrs/hnd lv, sequela',NULL),
	 ('Books','Occupant of 3-whl mv injured in collision w rail trn/veh',NULL),
	 ('Automotive','Dislocation of jaw, right side',NULL),
	 ('Industrial','Ankylosis, unspecified elbow',NULL),
	 ('Shoes','Chronic dacryocystitis of right lacrimal passage',NULL),
	 ('Garden','Toxic eff of nitrodrv/aminodrv of benzn/homolog, acc, init',NULL),
	 ('Clothing','Poisoning by other antidysrhythmic drugs, assault, sequela',NULL),
	 ('Grocery','Person outsd 3-whl mv inj in clsn w 2/3-whl mv in traf, sqla',NULL),
	 ('Automotive','Malignant neoplasm of spermatic cord',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Home','Osteomyelitis of vertebra, cervicothoracic region',NULL),
	 ('Books','Malignant neoplasm of female genital organ, unspecified',NULL),
	 ('Industrial','Fall into natrl body of water strk surfc cause oth inj, sqla',NULL),
	 ('Music','Nondisp fx of med condyle of unsp tibia, 7thQ',NULL),
	 ('Jewelry','Unsp fracture of first metacarpal bone, unsp hand, sequela',NULL),
	 ('Toys','Legal intervention involving other gas, bystander injured',NULL),
	 ('Toys','Disp fx of right tibial spine, init for opn fx type I/2',NULL),
	 ('Electronics','Puckering of macula, right eye',NULL),
	 ('Industrial','Syphilis of bone and joint',NULL),
	 ('Home','External constriction of lip, initial encounter',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Health','Other scleritis',NULL),
	 ('Home','Oth injury of dorsal artery of unspecified foot, sequela',NULL),
	 ('Kids','Benign neoplasm of scapula and long bones of unsp upper limb',NULL),
	 ('Outdoors','Lac w fb of back wall of thorax w/o penet thoracic cavity',NULL),
	 ('Outdoors','Other specified injuries of right foot',NULL),
	 ('Toys','Oth fracture of first lumbar vertebra, init for clos fx',NULL),
	 ('Electronics','Disp fx of proximal phalanx of thmb, subs for fx w nonunion',NULL),
	 ('Industrial','Oth specific joint derangements of unsp ankle, NEC',NULL),
	 ('Shoes','Unsp injury of blood vessels at wrs/hnd lv of left arm, subs',NULL),
	 ('Industrial','Individual with autosomal fragile site',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Industrial','Intraop hemor/hemtom of a ms structure comp a procedure',NULL),
	 ('Sports','Displ seg fx shaft of l tibia, subs for clos fx w delay heal',NULL),
	 ('Movies','Abrasion of penis, initial encounter',NULL),
	 ('Outdoors','Nondisp Rolando''s fracture, l hand, subs for fx w delay heal',NULL),
	 ('Tools','Burn of third degree of left knee, sequela',NULL),
	 ('Health','Displ oblique fx shaft of l femr, 7thH',NULL),
	 ('Grocery','Postimmunization arthropathy, right shoulder',NULL),
	 ('Computers','Asymptomatic varicose veins of lower extremities',NULL),
	 ('Baby','Inj extn musc/fasc/tend r mid finger at forarm lv, sequela',NULL),
	 ('Computers','Impaired fasting glucose',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Music','Nondisp fx of distal pole of navic bone of unsp wrist, init',NULL),
	 ('Movies','Minor laceration of left kidney, initial encounter',NULL),
	 ('Beauty','Unsp fx shaft of right tibia, subs for clos fx w nonunion',NULL),
	 ('Kids','Prph tear of medial meniscus, current injury, r knee, subs',NULL),
	 ('Health','Poisn by oth drug aff the autonm nervous sys, assault, init',NULL),
	 ('Clothing','Exudative age-rel mclr degn, bi, with actv chrdl neovas',NULL),
	 ('Sports','Superficial foreign body of left shoulder',NULL),
	 ('Electronics','Corrosion of unspecified degree of right upper arm, sequela',NULL),
	 ('Jewelry','Unsp injury of blood vessels at shldr/up arm, right arm',NULL),
	 ('Home','Smith''s fx left radius, subs for opn fx type I/2 w malunion',NULL);
INSERT INTO tienda.categorias (nombre_categoria,descripción,imagen) VALUES
	 ('Automotive','War operations involving rubber bullets, civilian, init',NULL),
	 ('Kids','Poisoning by antidiarrheal drugs, undetermined, sequela',NULL),
	 ('Automotive','Breakdown of int fix of bones of hand and fingers, init',NULL),
	 ('Beauty','Oth fx low end unsp femr, 7thN',NULL),
	 ('Computers','Hematoma of pinna, right ear',NULL),
	 ('Movies','Nondisp fx of less trochanter of unsp femr, 7thQ',NULL),
	 ('Games','External constriction of other part of head, subs encntr',NULL),
	 ('Home','Subluxation of MCP joint of right middle finger, subs',NULL),
	 ('Music','Unsp physl fx lower end unsp femur, subs for fx w routn heal',NULL),
	 ('Beauty','Unsp traumatic spondylolisthesis of fourth cervical vertebra',NULL);
