INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Rice - Basmati',44),
	 ('Sandwich Wrap',268),
	 ('Tomatoes - Hot House',62),
	 ('Mussels - Frozen',423),
	 ('Langers - Ruby Red Grapfruit',575),
	 ('Chocolate - Compound Coating',860),
	 ('Bacon Strip Precooked',685),
	 ('Pasta - Canelloni, Single Serve',870),
	 ('Horseradish Root',799),
	 ('Wine - Penfolds Koonuga Hill',837);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Capers - Ox Eye Daisy',683),
	 ('Beans - Kidney White',144),
	 ('Devonshire Cream',831),
	 ('Chinese Foods - Plain Fried Rice',213),
	 ('Soup - Knorr, Veg / Beef',437),
	 ('Crush - Grape, 355 Ml',801),
	 ('Veal - Heart',519),
	 ('Sunflower Seed Raw',860),
	 ('Wine - Charddonnay Errazuriz',538),
	 ('Lychee - Canned',159);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Chicken - Bones',955),
	 ('Club Soda - Schweppes, 355 Ml',974),
	 ('Mangoes',985),
	 ('Gelatine Powder',660),
	 ('Muffin Mix - Lemon Cranberry',284),
	 ('Yams',21),
	 ('Onions - Vidalia',879),
	 ('Squash - Acorn',611),
	 ('Cheese - Augre Des Champs',587),
	 ('Mousse - Mango',270);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - White, Riesling, Henry Of',544),
	 ('Soup - Cream Of Potato / Leek',92),
	 ('Soup - Campbells Broccoli',607),
	 ('Pear - Halves',559),
	 ('Wine - Malbec Trapiche Reserve',443),
	 ('Veal - Provimi Inside',508),
	 ('Lotus Leaves',729),
	 ('Veal - Shank, Pieces',873),
	 ('Wine - Red, Gamay Noir',26),
	 ('Island Oasis - Magarita Mix',854);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Energy Drink - Franks Original',260),
	 ('Energy Drink - Franks Pineapple',395),
	 ('Cheese - Brie,danish',287),
	 ('Chevere Logs',774),
	 ('Aspic - Amber',832),
	 ('Mackerel Whole Fresh',863),
	 ('Juice - Cranberry, 341 Ml',524),
	 ('Pepper - Paprika, Spanish',1000),
	 ('Cheese - Colby',72),
	 ('Octopus - Baby, Cleaned',506);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Corn Meal',639),
	 ('Creamers - 10%',441),
	 ('Juice - Cranberry 284ml',839),
	 ('Isomalt',738),
	 ('Gin - Gilbeys London, Dry',26),
	 ('Pork - Sausage Casing',629),
	 ('Chocolate - Semi Sweet, Calets',778),
	 ('English Muffin',747),
	 ('Beef Wellington',495),
	 ('Beef Striploin Aaa',265);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Tortillas - Flour, 12',351),
	 ('Lid - 3oz Med Rec',967),
	 ('Green Tea Refresher',269),
	 ('Lamb - Whole, Frozen',206),
	 ('Liners - Baking Cups',809),
	 ('Crab - Blue, Frozen',398),
	 ('Mushroom - Lg - Cello',913),
	 ('Soup - Beef, Base Mix',196),
	 ('Bread - Granary Small Pull',373),
	 ('Bread - Crusty Italian Poly',938);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Parsley Italian - Fresh',641),
	 ('Wine - White, Antinore Orvieto',779),
	 ('Broom And Brush Rack Black',472),
	 ('Apple - Custard',459),
	 ('Quinoa',170),
	 ('Pastrami',592),
	 ('Red Snapper - Fillet, Skin On',248),
	 ('Soup - Campbells, Lentil',488),
	 ('Beer - Molson Excel',155),
	 ('Peppercorns - Pink',405);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Glass Clear 8 Oz',994),
	 ('Fudge - Chocolate Fudge',132),
	 ('Pork - Inside',727),
	 ('Parsley Italian - Fresh',165),
	 ('Pepper - Cubanelle',932),
	 ('Bread - Flat Bread',900),
	 ('Sauce - Apple, Unsweetened',288),
	 ('Wine - Lamancha Do Crianza',428),
	 ('Lamb - Whole Head Off',712),
	 ('Wine - Remy Pannier Rose',40);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef - Ground, Extra Lean, Fresh',447),
	 ('Chinese Foods - Pepper Beef',282),
	 ('Cheese Cheddar Processed',539),
	 ('Nacho Chips',472),
	 ('Wine - Piper Heidsieck Brut',926),
	 ('Herb Du Provence - Primerba',96),
	 ('Mushroom - Lg - Cello',991),
	 ('Basil - Thai',553),
	 ('Soup - Boston Clam Chowder',22),
	 ('Wine - Red, Concha Y Toro',174);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Pastry - Raisin Muffin - Mini',856),
	 ('Salmon Steak - Cohoe 6 Oz',67),
	 ('Radish - Black, Winter, Organic',328),
	 ('Cassis',242),
	 ('Chicken - Ground',905),
	 ('Table Cloth 90x90 Colour',785),
	 ('Taro Root',123),
	 ('Fish - Scallops, Cold Smoked',518),
	 ('Doilies - 8, Paper',507),
	 ('Rum - White, Gg White',922);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Pepperoni Slices',409),
	 ('Energy Drink',125),
	 ('Eggplant - Asian',259),
	 ('Tea - Herbal Orange Spice',66),
	 ('Coffee - Frthy Coffee Crisp',110),
	 ('Tomatillo',556),
	 ('Arizona - Plum Green Tea',634),
	 ('Lamb Rack Frenched Australian',844),
	 ('Caviar - Salmon',413),
	 ('Wine - Maipo Valle Cabernet',233);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Ginger - Crystalized',543),
	 ('Truffle - Peelings',244),
	 ('Juice - Apple, 500 Ml',870),
	 ('Gin - Gilbeys London, Dry',518),
	 ('Shrimp - Prawn',431),
	 ('Wine - Chenin Blanc K.w.v.',436),
	 ('Wine - White, Antinore Orvieto',125),
	 ('Sobe - Lizard Fuel',91),
	 ('Appetizer - Escargot Puff',7),
	 ('Bandage - Flexible Neon',72);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Sobe - Orange Carrot',773),
	 ('Lobster - Tail 6 Oz',204),
	 ('Red Snapper - Fresh, Whole',337),
	 ('Chicken - Leg, Boneless',856),
	 ('Egg - Salad Premix',37),
	 ('Whmis Spray Bottle Graduated',470),
	 ('Island Oasis - Pina Colada',304),
	 ('Beer - Creemore',825),
	 ('Pork - Bacon, Sliced',437),
	 ('Tumeric',611);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Lamb - Whole Head Off',304),
	 ('Pork - Sausage, Medium',295),
	 ('Soup - Campbells - Chicken Noodle',536),
	 ('Tea - Green',915),
	 ('Dried Cherries',600),
	 ('Water - Green Tea Refresher',205),
	 ('Shrimp - 100 / 200 Cold Water',24),
	 ('Club Soda - Schweppes, 355 Ml',125),
	 ('Eggplant - Baby',617),
	 ('Yogurt - Cherry, 175 Gr',729);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Rice Paper',707),
	 ('Cleaner - Bleach',883),
	 ('Water Chestnut - Canned',198),
	 ('Ginger - Fresh',552),
	 ('Taro Leaves',842),
	 ('Arrowroot',488),
	 ('Star Fruit',404),
	 ('Wine - Cava Aria Estate Brut',993),
	 ('Anchovy Paste - 56 G Tube',847),
	 ('Cranberries - Fresh',706);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Tart Shells - Sweet, 3',736),
	 ('Salmon - Smoked, Sliced',926),
	 ('Pepper - Yellow Bell',335),
	 ('Tamarind Paste',776),
	 ('Veal - Tenderloin, Untrimmed',578),
	 ('Nut - Hazelnut, Ground, Natural',83),
	 ('Pineapple - Regular',897),
	 ('Wine - Sherry Dry Sack, William',925),
	 ('Heavy Duty Dust Pan',776),
	 ('Mix - Cocktail Strawberry Daiquiri',448);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Flour Dark Rye',96),
	 ('Carrots - Mini, Stem On',353),
	 ('Table Cloth 62x114 White',406),
	 ('Coffee Cup 8oz 5338cd',423),
	 ('Worcestershire Sauce',860),
	 ('Wine - Magnotta - Red, Baco',643),
	 ('Puree - Pear',822),
	 ('Beef - Tongue, Fresh',768),
	 ('Gelatine Leaves - Envelopes',972),
	 ('Stainless Steel Cleaner Vision',816);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Crackers - Graham',889),
	 ('Veal - Brisket, Provimi,bnls',692),
	 ('Flour - Bread',69),
	 ('Mix - Cappucino Cocktail',169),
	 ('Olives - Black, Pitted',564),
	 ('Napkin - Dinner, White',706),
	 ('Slt - Individual Portions',637),
	 ('Wine - Ej Gallo Sonoma',323),
	 ('Parasol Pick Stir Stick',423),
	 ('Chocolate - Dark',7);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Turnip - Mini',643),
	 ('Table Cloth 54x54 Colour',893),
	 ('Lettuce - Radicchio',158),
	 ('Turkey - Breast, Double',671),
	 ('Petit Baguette',221),
	 ('Tomatoes Tear Drop',973),
	 ('Chips - Miss Vickies',828),
	 ('Cafe Royale',16),
	 ('Juice - Clam, 46 Oz',782),
	 ('Sauce - Balsamic Viniagrette',149);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Ginsing - Fresh',121),
	 ('Sesame Seed Black',258),
	 ('Jerusalem Artichoke',401),
	 ('Fish - Artic Char, Cold Smoked',841),
	 ('Lemonade - Black Cherry, 591 Ml',357),
	 ('Wine - Red, Black Opal Shiraz',860),
	 ('Coffee Cup 16oz Foam',65),
	 ('7up Diet, 355 Ml',51),
	 ('Wine - Beringer Founders Estate',162),
	 ('White Baguette',631);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Spice - Greek 1 Step',394),
	 ('Chocolate - Semi Sweet',45),
	 ('Marjoram - Dried, Rubbed',927),
	 ('Coffee Cup 8oz 5338cd',962),
	 ('Vinegar - Champagne',252),
	 ('Island Oasis - Lemonade',988),
	 ('Bagelers - Cinn / Brown Sugar',367),
	 ('Fennel - Seeds',840),
	 ('Soup - Knorr, Veg / Beef',467),
	 ('Pickle - Dill',15);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Yukon Jack',416),
	 ('Extract - Raspberry',849),
	 ('Macaroons - Two Bite Choc',831),
	 ('Cookie Chocolate Chip With',522),
	 ('Onions - Red',377),
	 ('Beef - Eye Of Round',802),
	 ('French Pastry - Mini Chocolate',258),
	 ('Beer - Guiness',611),
	 ('Whmis Spray Bottle Graduated',731),
	 ('Syrup - Pancake',146);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Vermouth - Sweet, Cinzano',28),
	 ('Cheese - Goat',14),
	 ('Turkey - Ground. Lean',19),
	 ('Towel Multifold',725),
	 ('Syrup - Kahlua Chocolate',419),
	 ('Appetizer - Smoked Salmon / Dill',96),
	 ('Glucose',17),
	 ('Steam Pan - Half Size Deep',925),
	 ('Appetizer - Tarragon Chicken',378),
	 ('Greens Mustard',447);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Coffee - Espresso',601),
	 ('Onions - Spanish',866),
	 ('Kellogs Cereal In A Cup',176),
	 ('Pork - Bacon Cooked Slcd',906),
	 ('Mousse - Mango',641),
	 ('Pasta - Ravioli',684),
	 ('Chips - Miss Vickies',762),
	 ('Pork - Belly Fresh',881),
	 ('Pork - Hock And Feet Attached',787),
	 ('Appetizer - Lobster Phyllo Roll',990);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Appetizer - Mini Egg Roll, Shrimp',561),
	 ('Lid Tray - 12in Dome',259),
	 ('Wine - Red, Cooking',843),
	 ('Bread - Italian Sesame Poly',281),
	 ('Wine - Jaboulet Cotes Du Rhone',651),
	 ('Onions - Green',941),
	 ('Squid Ink',111),
	 ('Icecream - Dstk Cml And Fdg',321),
	 ('Oranges - Navel, 72',537),
	 ('Rum - Spiced, Captain Morgan',700);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Mangostein',773),
	 ('Cake Sheet Combo Party Pack',481),
	 ('Tea - Decaf Lipton',879),
	 ('Pail - 4l White, With Handle',808),
	 ('Fish - Atlantic Salmon, Cold',244),
	 ('Wine - White Cab Sauv.on',193),
	 ('Tomatoes - Roma',257),
	 ('Orange - Canned, Mandarin',632),
	 ('Tart Shells - Savory, 2',486),
	 ('Cheese - Goat With Herbs',273);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Aromat Spice / Seasoning',615),
	 ('Wine - Red, Cooking',303),
	 ('Mousse - Passion Fruit',867),
	 ('Bread - Sour Batard',324),
	 ('Squash - Guords',71),
	 ('Pie Filling - Pumpkin',68),
	 ('Cattail Hearts',330),
	 ('Milk - Chocolate 500ml',622),
	 ('Sauce - Demi Glace',679),
	 ('Soda Water - Club Soda, 355 Ml',783);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - Pinot Noir Latour',492),
	 ('Bread - Roll, Canadian Dinner',266),
	 ('Juice - Orange, 341 Ml',750),
	 ('Beef - Tongue, Fresh',907),
	 ('Salt - Celery',239),
	 ('Arizona - Plum Green Tea',909),
	 ('Pork - Caul Fat',670),
	 ('Beef - Rib Roast, Capless',831),
	 ('Bread - English Muffin',456),
	 ('Chocolate - Semi Sweet',408);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Spice - Pepper Portions',891),
	 ('Pasta - Tortellini, Fresh',16),
	 ('Mousse - Passion Fruit',736),
	 ('Oil - Peanut',830),
	 ('Wine - Alsace Gewurztraminer',449),
	 ('Cream - 18%',709),
	 ('Water - Evian 355 Ml',787),
	 ('Carroway Seed',4),
	 ('Fish - Artic Char, Cold Smoked',337),
	 ('Seedlings - Mix, Organic',385);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Danishes - Mini Raspberry',33),
	 ('V8 Splash Strawberry Banana',358),
	 ('Beef - Ox Tongue, Pickled',219),
	 ('Bagelers',774),
	 ('Bread - Sticks, Thin, Plain',440),
	 ('Soup - French Onion',109),
	 ('Zucchini - Mini, Green',274),
	 ('Pastry - Baked Cinnamon Stick',570),
	 ('Ice - Clear, 300 Lb For Carving',725),
	 ('Beets - Pickled',90);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Pepper - Green Thai',634),
	 ('Duck - Legs',229),
	 ('Potatoes - Parissienne',883),
	 ('Pepper - Scotch Bonnet',508),
	 ('Jerusalem Artichoke',377),
	 ('Numi - Assorted Teas',561),
	 ('Country Roll',387),
	 ('Extract - Rum',690),
	 ('Paper Towel Touchless',962),
	 ('Cheese - Brick With Pepper',396);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Bread Foccacia Whole',624),
	 ('Silicone Paper 16.5x24',360),
	 ('Turkey - Breast, Double',201),
	 ('Pomello',767),
	 ('Mustard - Individual Pkg',898),
	 ('Chicken - Base, Ultimate',27),
	 ('Foam Tray S2',837),
	 ('Anchovy Paste - 56 G Tube',831),
	 ('Bread - 10 Grain',968),
	 ('Juice Peach Nectar',321);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef - Top Butt',294),
	 ('Bagelers - Cinn / Brown Sugar',614),
	 ('Beer - Pilsner Urquell',381),
	 ('Wine - Vouvray Cuvee Domaine',597),
	 ('Melon - Watermelon, Seedless',274),
	 ('Capers - Ox Eye Daisy',606),
	 ('Soup - Campbells, Classic Chix',501),
	 ('Eggplant Italian',265),
	 ('Nut - Walnut, Pieces',187),
	 ('V8 - Vegetable Cocktail',970);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Chilli Paste, Hot Sambal Oelek',595),
	 ('Rice Paper',307),
	 ('Vegetable - Base',55),
	 ('Mousse - Mango',434),
	 ('Goat - Leg',449),
	 ('Soup - Campbells Broccoli',308),
	 ('Table Cloth 144x90 White',467),
	 ('Wine - Sherry Dry Sack, William',312),
	 ('Bread Country Roll',415),
	 ('Liqueur Banana, Ramazzotti',632);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef Wellington',405),
	 ('Sugar - Crumb',558),
	 ('Chips Potato Salt Vinegar 43g',954),
	 ('Broom And Brush Rack Black',328),
	 ('Lotus Leaves',683),
	 ('Juice - Orange, 341 Ml',610),
	 ('Chocolate Bar - Oh Henry',770),
	 ('Trout - Rainbow, Fresh',678),
	 ('Tart Shells - Savory, 3',398),
	 ('Tomato - Peeled Italian Canned',474);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Magnotta - Bel Paese White',709),
	 ('Veal - Insides, Grains',937),
	 ('Marsala - Sperone, Fine, D.o.c.',268),
	 ('Mince Meat - Filling',68),
	 ('Magnotta Bel Paese Red',864),
	 ('Lettuce - Boston Bib',445),
	 ('Doilies - 10, Paper',309),
	 ('Island Oasis - Wildberry',732),
	 ('Icecream Bar - Del Monte',819),
	 ('Juice - Cranberry, 341 Ml',903);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Crush - Orange, 355ml',369),
	 ('Veal - Eye Of Round',726),
	 ('Lid - 10,12,16 Oz',274),
	 ('Tart Shells - Sweet, 2',207),
	 ('Sponge Cake Mix - Vanilla',614),
	 ('Salt And Pepper Mix - Black',176),
	 ('Edible Flower - Mixed',328),
	 ('Dragon Fruit',456),
	 ('Flour - Bread',754),
	 ('Tofu - Soft',339);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Lemonade - Kiwi, 591 Ml',584),
	 ('Bread - Multigrain',295),
	 ('Sauce - Gravy, Au Jus, Mix',434),
	 ('Wine - White, Mosel Gold',915),
	 ('Table Cloth 81x81 White',491),
	 ('Venison - Racks Frenched',866),
	 ('Nectarines',792),
	 ('Walkers Special Old Whiskey',249),
	 ('Waffle Stix',723),
	 ('Apple - Macintosh',574);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Sauce - Marinara',192),
	 ('Pork - Bacon Cooked Slcd',860),
	 ('Pepper - Orange',628),
	 ('Chutney Sauce',890),
	 ('Potatoes - Pei 10 Oz',399),
	 ('Truffle Shells - Semi - Sweet',749),
	 ('Pasta - Angel Hair',740),
	 ('Veal - Striploin',544),
	 ('Tequila Rose Cream Liquor',647),
	 ('Truffle Cups Green',35);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Table Cloth 62x114 Colour',339),
	 ('Rabbit - Legs',724),
	 ('Bread - Granary Small Pull',856),
	 ('Nantucket Pine Orangebanana',888),
	 ('Tomatoes',911),
	 ('Juice - Tomato, 48 Oz',946),
	 ('Vinegar - Cider',480),
	 ('Ginger - Crystalized',892),
	 ('Dip - Tapenade',645),
	 ('Potatoes - Idaho 80 Count',557);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Cinnamon - Ground',118),
	 ('Chilli Paste, Ginger Garlic',984),
	 ('Tequila - Sauza Silver',275),
	 ('Turkey - Breast, Double',477),
	 ('Pears - Fiorelle',234),
	 ('Soup - Campbells Broccoli',28),
	 ('Pate Pans Yellow',615),
	 ('Table Cloth 62x120 Colour',874),
	 ('Bread - Bagels, Mini',336),
	 ('Coffee Beans - Chocolate',681);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Puree - Kiwi',213),
	 ('Juice - Apple, 1.36l',391),
	 ('Toothpick Frilled',508),
	 ('Cheese - Gouda',406),
	 ('Beef - Cow Feet Split',631),
	 ('Wine - Casillero Del Diablo',170),
	 ('Cleaner - Comet',175),
	 ('Tortillas - Flour, 12',411),
	 ('Sunflower Seed Raw',508),
	 ('Daves Island Stinger',877);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef - Striploin Aa',975),
	 ('Veal - Tenderloin, Untrimmed',620),
	 ('Chilli Paste, Hot Sambal Oelek',543),
	 ('Allspice - Jamaican',542),
	 ('Pie Filling - Cherry',234),
	 ('Flour - Masa De Harina Mexican',317),
	 ('Artichoke - Hearts, Canned',304),
	 ('Daikon Radish',965),
	 ('Wine - White, Cooking',353),
	 ('Oil - Truffle, Black',114);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Tortillas - Flour, 10',725),
	 ('Pastry - Choclate Baked',706),
	 ('Coffee - Cafe Moreno',611),
	 ('Salmon Atl.whole 8 - 10 Lb',899),
	 ('General Purpose Trigger',990),
	 ('Nori Sea Weed - Gold Label',725),
	 ('Pork - Butt, Boneless',793),
	 ('Potatoes - Idaho 80 Count',293),
	 ('Truffle Shells - Semi - Sweet',751),
	 ('Raspberries - Fresh',401);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef - Outside, Round',746),
	 ('Vermacelli - Sprinkles, Assorted',568),
	 ('Wine - Delicato Merlot',911),
	 ('Crab - Claws, Snow 16 - 24',632),
	 ('Steam Pan - Half Size Deep',10),
	 ('Star Anise, Whole',117),
	 ('Green Scrubbie Pad H.duty',932),
	 ('Flour - Semolina',223),
	 ('Wine - Two Oceans Cabernet',384),
	 ('Higashimaru Usukuchi Soy',423);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Jagermeister',127),
	 ('Chocolate - Milk, Callets',718),
	 ('Coffee - Espresso',517),
	 ('Country Roll',607),
	 ('Sprite, Diet - 355ml',301),
	 ('Fork - Plastic',295),
	 ('Pie Shells 10',534),
	 ('Bread - White, Sliced',253),
	 ('Rum - Spiced, Captain Morgan',236),
	 ('Juice - Clam, 46 Oz',182);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Water - Mineral, Natural',559),
	 ('Soup - Campbells Chili',149),
	 ('Wine - Alsace Gewurztraminer',611),
	 ('Cod - Salted, Boneless',620),
	 ('Wine - Shiraz South Eastern',354),
	 ('General Purpose Trigger',413),
	 ('Pastry - French Mini Assorted',177),
	 ('Wine - Red, Cabernet Sauvignon',442),
	 ('Wine - Delicato Merlot',478),
	 ('Energy Drink - Franks Original',494);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Mousse - Mango',732),
	 ('Ostrich - Prime Cut',39),
	 ('Flour - All Purpose',746),
	 ('Pastry - Apple Muffins - Mini',705),
	 ('Vodka - Lemon, Absolut',298),
	 ('Pepper - Gypsy Pepper',343),
	 ('Wine - Sauvignon Blanc Oyster',245),
	 ('Vol Au Vents',652),
	 ('Cheese - Cottage Cheese',145),
	 ('Cumin - Whole',480);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef Tenderloin Aaa',263),
	 ('Chicken - Whole Roasting',517),
	 ('Cookies - Englishbay Wht',659),
	 ('Towels - Paper / Kraft',478),
	 ('Squeeze Bottle',132),
	 ('Relish',470),
	 ('Juice - Apple, 1.36l',510),
	 ('Juice - Orange, Concentrate',979),
	 ('Sugar - Icing',948),
	 ('Cheese - St. Paulin',794);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Mushroom - Enoki, Fresh',219),
	 ('Butter - Salted',140),
	 ('Soy Protein',391),
	 ('Peas - Pigeon, Dry',720),
	 ('Bag - Regular Kraft 20 Lb',747),
	 ('Cheese - Swiss',25),
	 ('Salmon - Sockeye Raw',355),
	 ('Muffin Hinge - 211n',159),
	 ('Hagen Daza - Dk Choocolate',1000),
	 ('Skirt - 24 Foot',510);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - Cotes Du Rhone',378),
	 ('Calypso - Pineapple Passion',994),
	 ('Mints - Striped Red',742),
	 ('Veal - Insides, Grains',260),
	 ('Crab - Claws, 26 - 30',948),
	 ('Wine - Zinfandel California 2002',117),
	 ('Energy Drink',700),
	 ('Container - Clear 32 Oz',358),
	 ('Beer - Upper Canada Light',238),
	 ('Wanton Wrap',126);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Vinegar - Raspberry',445),
	 ('Mushroom - Porcini Frozen',75),
	 ('Doilies - 8, Paper',997),
	 ('Soda Water - Club Soda, 355 Ml',160),
	 ('Remy Red Berry Infusion',576),
	 ('Juice - Mango',981),
	 ('Chef Hat 20cm',635),
	 ('Cup Translucent 9 Oz',763),
	 ('Lentils - Green Le Puy',949),
	 ('Lotus Rootlets - Canned',837);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Soup Campbells Mexicali Tortilla',940),
	 ('Cheese - Sheep Milk',878),
	 ('Beer - Blue',376),
	 ('Bandage - Flexible Neon',607),
	 ('Water - Green Tea Refresher',918),
	 ('Flower - Daisies',171),
	 ('Pepper - Paprika, Spanish',681),
	 ('Sauce - Hp',328),
	 ('Chocolate - Dark',426),
	 ('Cheese - Cheddarsliced',700);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Noodles - Steamed Chow Mein',911),
	 ('Beef Striploin Aaa',556),
	 ('Toothpick Frilled',9),
	 ('Muffin - Bran Ind Wrpd',132),
	 ('Lettuce - Romaine, Heart',919),
	 ('Wine - Alsace Gewurztraminer',563),
	 ('Wine - Magnotta, White',25),
	 ('Shrimp - Black Tiger 16/20',463),
	 ('Chips - Potato Jalapeno',145),
	 ('Sugar - Splenda Sweetener',708);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Plums - Red',660),
	 ('Ecolab - Orange Frc, Cleaner',190),
	 ('Cheese - Mozzarella, Buffalo',121),
	 ('Onions - Red Pearl',376),
	 ('Table Cloth 62x120 White',822),
	 ('Ham - Smoked, Bone - In',586),
	 ('Lychee - Canned',779),
	 ('Fish - Halibut, Cold Smoked',127),
	 ('Wine - Redchard Merritt',789),
	 ('Olives - Green, Pitted',761);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Onions - White',859),
	 ('Soup - Cream Of Broccoli, Dry',269),
	 ('Foam Tray S2',230),
	 ('Wine - Magnotta - Cab Franc',961),
	 ('Salmon - Smoked, Sliced',77),
	 ('Star Anise, Whole',630),
	 ('Mushroom Morel Fresh',396),
	 ('Beef - Eye Of Round',176),
	 ('Neckerchief Blck',491),
	 ('Bread - Calabrese Baguette',408);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Bread - Roll, Calabrese',847),
	 ('Filling - Mince Meat',289),
	 ('Lamb - Whole, Fresh',785),
	 ('Wine - Magnotta - Red, Baco',914),
	 ('Wine - Port Late Bottled Vintage',669),
	 ('Napkin - Cocktail,beige 2 - Ply',600),
	 ('Jolt Cola - Electric Blue',836),
	 ('Bacardi Breezer - Tropical',203),
	 ('Soup - Knorr, French Onion',344),
	 ('V8 Splash Strawberry Banana',213);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Sword Pick Asst',915),
	 ('Veal - Heart',126),
	 ('Beer - Blue Light',566),
	 ('Cheese - Parmesan Cubes',703),
	 ('Pork - Sausage, Medium',978),
	 ('Bread Crumbs - Panko',117),
	 ('Chips Potato Swt Chilli Sour',936),
	 ('Pepper - Paprika, Hungarian',325),
	 ('Cup - 8oz Coffee Perforated',505),
	 ('Muffin Carrot - Individual',3);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Pasta - Canelloni',750),
	 ('Red Currant Jelly',228),
	 ('Scallops - In Shell',338),
	 ('Pineapple - Golden',697),
	 ('Chicken - Leg, Fresh',880),
	 ('Beer - Labatt Blue',583),
	 ('Pear - Prickly',477),
	 ('Lettuce - Romaine',951),
	 ('Chinese Foods - Chicken',963),
	 ('Red Cod Fillets - 225g',42);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Langers - Mango Nectar',496),
	 ('Icecream - Dstk Super Cone',476),
	 ('Sugar - Icing',575),
	 ('Sauce - Bernaise, Mix',249),
	 ('Pie Shell - 5',673),
	 ('Mushroom - Enoki, Dry',495),
	 ('Lamb - Rack',230),
	 ('Ostrich - Prime Cut',629),
	 ('Bagelers',55),
	 ('Soup - Knorr, Chicken Noodle',3);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Quail - Whole, Boneless',960),
	 ('Mayonnaise - Individual Pkg',334),
	 ('Coffee - Espresso',111),
	 ('Lamb - Shoulder',286),
	 ('Rum - Light, Captain Morgan',368),
	 ('Olives - Stuffed',545),
	 ('Sauce - Bernaise, Mix',937),
	 ('Wine - Red, Mosaic Zweigelt',681),
	 ('Water - Mineral, Natural',197),
	 ('Squash - Butternut',625);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Bagelers',234),
	 ('Radish - Pickled',570),
	 ('Hot Choc Vending',37),
	 ('Soup - Boston Clam Chowder',692),
	 ('Trueblue - Blueberry Cranberry',470),
	 ('Bread - French Stick',775),
	 ('Lentils - Green Le Puy',190),
	 ('Vermouth - Sweet, Cinzano',696),
	 ('Water - San Pellegrino',218),
	 ('Table Cloth 62x120 Colour',606);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Scrubbie - Scotchbrite Hand Pad',303),
	 ('Water Chestnut - Canned',553),
	 ('Everfresh Products',893),
	 ('Orange - Canned, Mandarin',859),
	 ('Cheese - Cheddarsliced',856),
	 ('Pasta - Penne, Lisce, Dry',550),
	 ('Gatorade - Xfactor Berry',751),
	 ('Flour - All Purpose',361),
	 ('Jam - Blackberry, 20 Ml Jar',453),
	 ('The Pop Shoppe - Root Beer',484);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - White, Schroder And Schyl',534),
	 ('Pineapple - Golden',802),
	 ('Beef - Rib Eye Aaa',74),
	 ('Everfresh Products',53),
	 ('Oil - Sunflower',229),
	 ('Beer - Muskoka Cream Ale',630),
	 ('Bagelers',38),
	 ('Glass - Wine, Plastic, Clear 5 Oz',11),
	 ('Beer - Corona',280),
	 ('Appetizer - Mango Chevre',132);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - Tribal Sauvignon',415),
	 ('Bacardi Mojito',479),
	 ('Carbonated Water - White Grape',740),
	 ('Sprouts - Corn',722),
	 ('Veal - Slab Bacon',813),
	 ('Jam - Strawberry, 20 Ml Jar',184),
	 ('Quail - Whole, Boneless',485),
	 ('Cauliflower',348),
	 ('French Pastries',651),
	 ('Pastry - Apple Muffins - Mini',931);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Rabbit - Whole',901),
	 ('Mace Ground',661),
	 ('Lettuce - Mini Greens, Whole',145),
	 ('Creme De Cacao White',92),
	 ('Rambutan',307),
	 ('Appetizer - Smoked Salmon / Dill',897),
	 ('Pork - Hock And Feet Attached',703),
	 ('Sausage - Breakfast',777),
	 ('Napkin - Beverage 1 Ply',635),
	 ('Energy Drink - Redbull 355ml',406);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Oil - Margarine',587),
	 ('Pepper - Paprika, Spanish',194),
	 ('Soup - Tomato Mush. Florentine',731),
	 ('Maple Syrup',801),
	 ('Pimento - Canned',1000),
	 ('Soup Bowl Clear 8oz92008',295),
	 ('Blue Curacao - Marie Brizard',428),
	 ('Energy Drink - Redbull 355ml',643),
	 ('Banana - Leaves',226),
	 ('Lettuce - Red Leaf',17);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Cheese - Fontina',866),
	 ('Puree - Strawberry',540),
	 ('Cabbage - Savoy',668),
	 ('Sambuca - Ramazzotti',268),
	 ('The Pop Shoppe - Grape',25),
	 ('Wine - Shiraz South Eastern',551),
	 ('Bread - Bagels, Mini',207),
	 ('Hagen Daza - Dk Choocolate',944),
	 ('Potatoes - Mini Red',579),
	 ('Bar Energy Chocchip',788);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Coffee - Hazelnut Cream',144),
	 ('Pickle - Dill',204),
	 ('Galliano',584),
	 ('Oil - Coconut',86),
	 ('Bread - Hot Dog Buns',61),
	 ('Monkfish Fresh - Skin Off',805),
	 ('Veal - Brisket, Provimi, Bone - In',712),
	 ('Wine - Magnotta - Cab Franc',785),
	 ('Bread - Bistro Sour',837),
	 ('Oregano - Fresh',983);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Cornish Hen',867),
	 ('Beef - Ox Tail, Frozen',138),
	 ('Soup - Campbells Tomato Ravioli',840),
	 ('Chicken - Wieners',340),
	 ('Goulash Seasoning',850),
	 ('Petite Baguette',896),
	 ('Bulgar',46),
	 ('Table Cloth 53x69 White',264),
	 ('Wine - Red, Lurton Merlot De',197),
	 ('Bread Base - Italian',96);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Flour - Whole Wheat',678),
	 ('Capers - Ox Eye Daisy',70),
	 ('Wine - Red, Colio Cabernet',235),
	 ('Cheese Cloth No 60',368),
	 ('Wine - Pinot Grigio Collavini',970),
	 ('Butter - Salted',155),
	 ('Garam Marsala',482),
	 ('Grapes - Black',220),
	 ('Mountain Dew',890),
	 ('Monkfish - Fresh',788);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Muffin Hinge 117n',58),
	 ('Vinegar - Champagne',153),
	 ('Dehydrated Kelp Kombo',722),
	 ('Nantucket Orange Juice',104),
	 ('Wakami Seaweed',188),
	 ('Flavouring Vanilla Artificial',879),
	 ('Chips - Miss Vickies',188),
	 ('Wine - Touraine Azay - Le - Rideau',596),
	 ('Bread Ww Cluster',547),
	 ('Syrup - Chocolate',493);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Potatoes - Purple, Organic',297),
	 ('Wine - Magnotta - Pinot Gris Sr',301),
	 ('Mustard - Pommery',597),
	 ('Tomato Puree',575),
	 ('Sauce - Marinara',627),
	 ('Maintenance Removal Charge',156),
	 ('Bread - Granary Small Pull',84),
	 ('Wine - Cava Aria Estate Brut',497),
	 ('Chickhen - Chicken Phyllo',626),
	 ('Wine - Blue Nun Qualitatswein',288);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Glucose',337),
	 ('Flower - Commercial Spider',4),
	 ('Juice - Orange, 341 Ml',652),
	 ('Soup - Boston Clam Chowder',524),
	 ('Venison - Racks Frenched',164),
	 ('Veal - Brisket, Provimi, Bone - In',56),
	 ('Vinegar - Red Wine',607),
	 ('Sorrel - Fresh',679),
	 ('Figs',598),
	 ('Piping Jelly - All Colours',607);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Fish - Bones',193),
	 ('Cheese - Brie, Triple Creme',43),
	 ('Muffin - Mix - Mango Sour Cherry',809),
	 ('Pie Filling - Apple',251),
	 ('Oil - Macadamia',14),
	 ('Salt - Celery',979),
	 ('Lettuce - California Mix',85),
	 ('Sprouts - China Rose',114),
	 ('Chicken - Ground',288),
	 ('Lemonade - Mandarin, 591 Ml',626);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Coffee Decaf Colombian',114),
	 ('Butter - Unsalted',348),
	 ('Beets',598),
	 ('Bouillion - Fish',633),
	 ('Artichokes - Knobless, White',701),
	 ('Ecolab - Balanced Fusion',149),
	 ('Lighter - Bbq',104),
	 ('Pepper - Black, Whole',699),
	 ('Schnappes - Peach, Walkers',234),
	 ('Squid - U 5',938);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - White, Chardonnay',919),
	 ('Lid - 10,12,16 Oz',439),
	 ('Lobster - Cooked',271),
	 ('Banana',880),
	 ('Wine - Vouvray Cuvee Domaine',525),
	 ('Kellogs Special K Cereal',591),
	 ('Milkettes - 2%',705),
	 ('Pork - Loin, Bone - In',308),
	 ('Soup - Campbells, Classic Chix',758),
	 ('Evaporated Milk - Skim',209);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Beef - Diced',554),
	 ('Apple - Granny Smith',77),
	 ('Cake - Mini Potato Pancake',827),
	 ('Veal - Eye Of Round',838),
	 ('Pepper - Chili Powder',742),
	 ('Oil - Cooking Spray',811),
	 ('Wine - Clavet Saint Emilion',969),
	 ('Sauce - Chili',379),
	 ('Cinnamon - Stick',510),
	 ('Pears - Bosc',14);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Cake - Mini Potato Pancake',870),
	 ('Pastry - Plain Baked Croissant',967),
	 ('Gelatine Powder',638),
	 ('Beef - Baby, Liver',751),
	 ('Danishes - Mini Raspberry',78),
	 ('Wine - Two Oceans Cabernet',601),
	 ('Wine - Sicilia Igt Nero Avola',892),
	 ('Brandy - Bar',679),
	 ('Wine - Rhine Riesling Wolf Blass',873),
	 ('Cake - Dulce De Leche',436);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Nut - Pecan, Pieces',687),
	 ('Bouillion - Fish',13),
	 ('Bread - 10 Grain',641),
	 ('Beef - Top Sirloin',565),
	 ('Jam - Strawberry, 20 Ml Jar',925),
	 ('Tart - Butter Plain Squares',206),
	 ('Gingerale - Schweppes, 355 Ml',990),
	 ('Mushroom - Morel Frozen',91),
	 ('Flower - Commercial Bronze',196),
	 ('Bread - Sour Batard',749);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Soup Campbells - Italian Wedding',293),
	 ('Cheese Cheddar Processed',639),
	 ('Pasta - Orzo, Dry',691),
	 ('Chocolate - White',801),
	 ('Tobasco Sauce',917),
	 ('Sesame Seed',369),
	 ('Noodles - Steamed Chow Mein',117),
	 ('Soup - Campbells - Chicken Noodle',52),
	 ('Oil - Peanut',133),
	 ('Steam Pan - Half Size Deep',376);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('The Pop Shoppe - Cream Soda',577),
	 ('Cheese - St. Paulin',990),
	 ('Sprouts - China Rose',55),
	 ('Milk - 2%',746),
	 ('Wine - Periguita Fonseca',397),
	 ('Wine - Red, Antinori Santa',227),
	 ('Walkers Special Old Whiskey',140),
	 ('Wine - Casablanca Valley',233),
	 ('Smirnoff Green Apple Twist',710),
	 ('Wine - Red, Cabernet Sauvignon',393);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Sprouts - China Rose',156),
	 ('Milk - Chocolate 250 Ml',888),
	 ('Pepper - Julienne, Frozen',78),
	 ('Broom - Push',828),
	 ('Nantucket Apple Juice',185),
	 ('Veal - Bones',381),
	 ('Corn - Mini',734),
	 ('Jolt Cola',729),
	 ('Pectin',847),
	 ('Sloe Gin - Mcguinness',384);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Squeeze Bottle',560),
	 ('Water - Perrier',666),
	 ('Sprouts - Corn',392),
	 ('Puree - Mocha',456),
	 ('Canadian Emmenthal',699),
	 ('Tea - Apple Green Tea',479),
	 ('Wine - Barolo Fontanafredda',247),
	 ('Veal - Leg',967),
	 ('Tomatoes - Cherry, Yellow',441),
	 ('Wine - Savigny - Les - Beaune',651);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Flour - Fast / Rapid',202),
	 ('Soup - Campbells Tomato Ravioli',89),
	 ('Banana Turning',702),
	 ('Grenadillo',34),
	 ('Wine - Baron De Rothschild',667),
	 ('Sea Bass - Whole',128),
	 ('Passion Fruit',804),
	 ('Juice - Cranberry 284ml',564),
	 ('Potatoes - Yukon Gold, 80 Ct',77),
	 ('Wine - Red, Concha Y Toro',50);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Praline Paste',543),
	 ('Beer - Camerons Cream Ale',58),
	 ('Rice - Basmati',978),
	 ('Jam - Strawberry, 20 Ml Jar',116),
	 ('Wine - Red, Marechal Foch',268),
	 ('Juice - Prune',283),
	 ('Cream - 10%',981),
	 ('Pop Shoppe Cream Soda',71),
	 ('Salmon - Atlantic, No Skin',518),
	 ('Syrup - Monin, Irish Cream',537);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Muffin - Mix - Mango Sour Cherry',864),
	 ('Cheese - Bakers Cream Cheese',224),
	 ('Banana',779),
	 ('Spice - Greek 1 Step',914),
	 ('Muffin Mix - Banana Nut',956),
	 ('Appetizer - Veg Assortment',325),
	 ('Boogies',331),
	 ('Cheese - Cheddar, Medium',913),
	 ('Cheese - Oka',764),
	 ('Veal - Slab Bacon',784);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Nutmeg - Ground',220),
	 ('Sprouts - China Rose',991),
	 ('Monkfish Fresh - Skin Off',721),
	 ('Carbonated Water - Orange',161),
	 ('Flower - Dish Garden',753),
	 ('Nantucket - Kiwi Berry Cktl.',623),
	 ('Muffin Batt - Choc Chk',561),
	 ('Pepperoni Slices',106),
	 ('Flower - Potmums',213),
	 ('Table Cloth 53x53 White',331);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - Sogrape Mateus Rose',400),
	 ('Sugar Thermometer',440),
	 ('Wine - Vineland Estate Semi - Dry',45),
	 ('Island Oasis - Sweet And Sour Mix',991),
	 ('Roe - Flying Fish',883),
	 ('Turnip - Mini',765),
	 ('Carbonated Water - White Grape',163),
	 ('Wine - Red, Cooking',495),
	 ('Wine - Red, Metus Rose',888),
	 ('Beef - Bones, Marrow',607);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Bagelers - Cinn / Brown Sugar',717),
	 ('Quail - Whole, Bone - In',419),
	 ('Turnip - White',796),
	 ('Peas - Pigeon, Dry',162),
	 ('Pails With Lids',873),
	 ('Butter Balls Salted',837),
	 ('Rambutan',650),
	 ('Stock - Veal, White',852),
	 ('Beer - Blue',361),
	 ('Sprouts - Pea',391);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Tea - Black Currant',342),
	 ('Kolrabi',746),
	 ('Stock - Fish',24),
	 ('Soap - Pine Sol Floor Cleaner',392),
	 ('Oil - Grapeseed Oil',201),
	 ('Pork - Backfat',744),
	 ('Fish - Bones',685),
	 ('Cheese - Le Cheve Noir',132),
	 ('Thyme - Dried',871),
	 ('Macaroons - Two Bite Choc',653);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Nut - Hazelnut, Ground, Natural',478),
	 ('Bread - Mini Hamburger Bun',992),
	 ('Cake - Cheese Cake 9 Inch',210),
	 ('Crab - Back Fin Meat, Canned',323),
	 ('Pepper - Red Chili',614),
	 ('Bread - Crusty Italian Poly',495),
	 ('Pop - Club Soda Can',823),
	 ('Bagel - Everything Presliced',864),
	 ('Beef - Tongue, Fresh',984),
	 ('Milk 2% 500 Ml',77);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Soup - Campbells - Tomato',168),
	 ('Carbonated Water - Blackcherry',807),
	 ('Pepsi - 600ml',561),
	 ('Beans - Yellow',369),
	 ('Chinese Foods - Cantonese',918),
	 ('Potatoes - Yukon Gold, 80 Ct',748),
	 ('Gelatine Powder',527),
	 ('Wine - Ej Gallo Sierra Valley',95),
	 ('Pepper - Julienne, Frozen',26),
	 ('Tomatoes - Grape',142);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Sugar - Monocystal / Rock',159),
	 ('Basil - Primerba, Paste',700),
	 ('Wine - Delicato Merlot',222),
	 ('Pie Filling - Apple',680),
	 ('Pasta - Cheese / Spinach Bauletti',318),
	 ('Glass Clear 8 Oz',597),
	 ('Myers Planters Punch',731),
	 ('Milk - 1%',229),
	 ('Towel Multifold',532),
	 ('Banana Turning',313);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - Spumante Bambino White',918),
	 ('Yoplait - Strawbrasp Peac',704),
	 ('Water Chestnut - Canned',898),
	 ('Wine - Kwv Chenin Blanc South',468),
	 ('Tea - Apple Green Tea',310),
	 ('Sauce - Soya, Dark',127),
	 ('Sambuca Cream',468),
	 ('Coffee - Irish Cream',633),
	 ('Vinegar - Red Wine',248),
	 ('Pork Loin Cutlets',360);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Artichoke - Fresh',506),
	 ('Wood Chips - Regular',619),
	 ('Pork - Bacon Cooked Slcd',847),
	 ('Soupfoamcont12oz 112con',439),
	 ('Coffee Cup 12oz 5342cd',609),
	 ('Wine - George Duboeuf Rose',806),
	 ('Oil - Coconut',160),
	 ('Sausage - Andouille',194),
	 ('Cleaner - Comet',920),
	 ('Oil - Avocado',400);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Spaghetti Squash',592),
	 ('Dc - Sakura Fu',999),
	 ('Cleaner - Comet',679),
	 ('Muffin Mix - Chocolate Chip',692),
	 ('Apple - Fuji',442),
	 ('Cheese - Parmesan Cubes',637),
	 ('Alize Red Passion',163),
	 ('Wine - Sauvignon Blanc Oyster',594),
	 ('Cardamon Seed / Pod',819),
	 ('Fireball Whisky',960);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Wine - Magnotta - Cab Franc',981),
	 ('Rum - Dark, Bacardi, Black',827),
	 ('Cup - 6oz, Foam',445),
	 ('Hersey Shakes',830),
	 ('Cleaner - Pine Sol',906),
	 ('Juice - Clam, 46 Oz',140),
	 ('Celery Root',636),
	 ('Wine - Rosso Del Veronese Igt',480),
	 ('Teriyaki Sauce',685),
	 ('Wine - Port Late Bottled Vintage',279);
INSERT INTO tienda.productos (nombre_productos,id_categoria) VALUES
	 ('Sauce - Ranch Dressing',691),
	 ('Pasta - Fett Alfredo, Single Serve',615),
	 ('Flavouring - Orange',372),
	 ('Wine - Vineland Estate Semi - Dry',257),
	 ('Propel Sport Drink',597),
	 ('Ginger - Ground',983),
	 ('Oil - Olive Bertolli',737),
	 ('Artichokes - Knobless, White',913),
	 ('Salt - Sea',780),
	 ('Truffle Shells - Semi - Sweet',669);
