INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('73822 Westerfield Avenue','Scottsdale'),
	 ('5 Reindahl Avenue','Zhangjiaji'),
	 ('0422 Laurel Drive','Kromasan'),
	 ('90 Manley Center','Fangshan'),
	 ('8041 Barnett Road','Tenancingo'),
	 ('98532 Amoth Center','Nkongsamba'),
	 ('943 Sycamore Trail','Shangsha'),
	 ('00 Pearson Plaza','Bazha'),
	 ('69958 Vernon Hill','Malá Strana'),
	 ('9 Spaight Lane','Kongoussi');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('470 Ronald Regan Lane','Chiang Rai'),
	 ('7979 Walton Center','San Quintin'),
	 ('0886 Carpenter Center','Belgorod'),
	 ('853 Kinsman Street','Starokucherganovka'),
	 ('98949 Sherman Terrace','Rozhnyativ'),
	 ('4540 Ronald Regan Road','Kayan'),
	 ('3 Superior Crossing','Bzenec'),
	 ('88714 Garrison Drive','Jinli'),
	 ('69387 Golf View Junction','Betania'),
	 ('21014 Red Cloud Place','Maliang');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('8678 Moose Plaza','Pereyaslav-Khmel’nyts’kyy'),
	 ('66 Artisan Plaza','San Isidro'),
	 ('0641 Haas Pass','Saltsjö-Boo'),
	 ('2 1st Point','Borås'),
	 ('86 Havey Center','Qushi’an'),
	 ('6 Drewry Trail','Sukamaju'),
	 ('6286 Linden Crossing','Adolfo Lopez Mateos'),
	 ('7 Michigan Hill','Saraburi'),
	 ('87304 Grayhawk Drive','Jampang Tengah'),
	 ('82142 Mifflin Place','Gunungmanik');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('65495 Westerfield Center','Sabae'),
	 ('83 Shoshone Lane','Tapas'),
	 ('539 Mendota Terrace','Al Jawādīyah'),
	 ('43656 Mariners Cove Pass','Sa''dah'),
	 ('5 Lakeland Place','Bula'),
	 ('13030 Brentwood Lane','Taraju'),
	 ('95314 Fallview Road','Dehui'),
	 ('9253 Gulseth Pass','Raciążek'),
	 ('4 Dunning Way','Ha’erlong'),
	 ('5685 Jenifer Trail','Wamba');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('39 Thackeray Crossing','Barão de São Miguel'),
	 ('8109 Ohio Circle','Huineno'),
	 ('1995 Dottie Circle','Pangushan'),
	 ('8 Fairfield Center','Salcedo'),
	 ('64876 Chive Alley','Lordegān'),
	 ('3613 Briar Crest Place','Ajman'),
	 ('1752 Melvin Center','Zarya'),
	 ('01231 Sauthoff Center','Chenchang'),
	 ('69249 Gateway Plaza','Vilarinho das Cambas'),
	 ('00 Hazelcrest Circle','Hantai');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('520 Pennsylvania Drive','Berat'),
	 ('861 Rutledge Junction','Florida'),
	 ('59 Dahle Avenue','Graz'),
	 ('5353 Kensington Plaza','Al ‘Ayzarīyah'),
	 ('10 Orin Circle','Neringa'),
	 ('5182 Atwood Trail','Haarlem'),
	 ('9 American Ash Pass','Santander'),
	 ('1 Fairview Place','Houston'),
	 ('0746 Ridgeway Road','Pictou'),
	 ('65284 Drewry Hill','Pakuwon');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('827 Blaine Avenue','Novaya Usman’'),
	 ('4 Harbort Street','Patnongon'),
	 ('3695 Orin Parkway','Bururi'),
	 ('4 Acker Crossing','Tiout'),
	 ('7 Caliangt Court','Dārayyā'),
	 ('4 Pennsylvania Trail','Shejiang'),
	 ('9359 Cordelia Trail','San Bartolomé Milpas Altas'),
	 ('320 Oakridge Park','Banjar'),
	 ('9635 Kropf Crossing','Liwan'),
	 ('6040 Riverside Circle','Ochla');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('7 Fallview Park','Montego Bay'),
	 ('96 Pine View Plaza','Bengtsfors'),
	 ('030 Summer Ridge Hill','Tangcun'),
	 ('28472 Caliangt Alley','Ziway'),
	 ('33314 Holy Cross Terrace','Aţ Ţīrah'),
	 ('461 Eastlawn Point','Sioux Falls'),
	 ('6630 Hauk Place','Koesan'),
	 ('2879 Evergreen Trail','Velykoploske'),
	 ('2929 Comanche Avenue','Shushenskoye'),
	 ('169 Miller Avenue','Jiazhuyuan');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('7 Hallows Point','Paris 14'),
	 ('9748 Arkansas Point','Secunda'),
	 ('9 Orin Court','Tianhe'),
	 ('217 Upham Point','Padaan'),
	 ('36906 Blaine Way','Mancos'),
	 ('808 8th Trail','Shisui'),
	 ('8 Melby Court','Alcaria da Serra'),
	 ('719 Vera Parkway','Sigay'),
	 ('8062 Waywood Drive','Oetutulul'),
	 ('2846 Northview Point','Vierzon');
INSERT INTO tienda.tienda (dirección,ciudad) VALUES
	 ('97615 Drewry Hill','Billdal'),
	 ('2292 Larry Pass','Linköping'),
	 ('4714 Express Drive','Bucaramanga'),
	 ('98 Reindahl Street','Municipio de Copacabana'),
	 ('560 Susan Trail','Tingping'),
	 ('3 Blue Bill Park Crossing','Zimovniki'),
	 ('8 Dovetail Drive','Budapest'),
	 ('1 Pennsylvania Crossing','Frydek'),
	 ('563 Moose Plaza','Looc'),
	 ('6290 Oriole Crossing','Fukuchiyama');
